workstation/stretch/securedrop-client_0.0.8_all.deb, workstation/stretch/securedrop-proxy_0.1.4_all.deb
Originally released by @creviera in
https://github.com/freedomofpress/infrastructure-deb-packages-lfs/commit/ea9705a35660c522f22662ea4ae35c4e8d565e16
=> Adds securedrop-client-0.0.8 and securedrop-proxy-0.1.4

workstation/stretch/linux-headers-4.14.128-grsec_4.14.128-grsec-1_amd64.deb, workstation/stretch/linux-image-4.14.128-grsec_4.14.128-grsec-1_amd64.deb, workstation/stretch/securedrop-workstation-grsec_4.14.128-1_amd64.deb
Adds 4.14.128 kernel image and header, as well as changes to securedrop-workstation-grsec metapackage proposed in https://github.com/freedomofpress/securedrop-debian-packaging/pull/60
=> Bump workstation grsec kernels to 4.14.128

core/xenial/linux-firmware-image-4.4.167-grsec_4.4.167-grsec-1_amd64.deb, core/xenial/linux-firmware-image-4.4.177-grsec_4.4.177-grsec-1_amd64.deb, core/xenial/linux-firmware-image-4.4.182-grsec_4.4.182-grsec-1_amd64.deb, core/xenial/linux-image-4.4.167-grsec_4.4.167-grsec-1_amd64.deb, core/xenial/linux-image-4.4.177-grsec_4.4.177-grsec-1_amd64.deb, core/xenial/linux-image-4.4.182-grsec_4.4.182-grsec-1_amd64.deb, core/xenial/ossec-agent-3.0.0-amd64.deb, core/xenial/ossec-server-3.0.0-amd64.deb, core/xenial/securedrop-app-code_0.13.0+xenial_amd64.deb, core/xenial/securedrop-app-code_0.13.1+xenial_amd64.deb, core/xenial/securedrop-config-0.1.3+0.13.0-amd64.deb, core/xenial/securedrop-config-0.1.3+0.13.1-amd64.deb, core/xenial/securedrop-grsec-4.4.167-amd64.deb, core/xenial/securedrop-grsec-4.4.177-amd64.deb, core/xenial/securedrop-grsec-4.4.182-amd64.deb, core/xenial/securedrop-keyring-0.1.2+0.13.0-amd64.deb, core/xenial/securedrop-keyring-0.1.2+0.13.1-amd64.deb, core/xenial/securedrop-ossec-agent-3.0.0+0.13.0-amd64.deb, core/xenial/securedrop-ossec-agent-3.0.0+0.13.1-amd64.deb, core/xenial/securedrop-ossec-server-3.0.0+0.13.0-amd64.deb, core/xenial/securedrop-ossec-server-3.0.0+0.13.1-amd64.deb, core/xenial/tor-geoipdb_0.3.5.7-1~xenial+1_all.deb, core/xenial/tor-geoipdb_0.3.5.8-1~xenial+1_all.deb, core/xenial/tor_0.3.5.7-1~xenial+1_amd64.deb, core/xenial/tor_0.3.5.8-1~xenial+1_amd64.deb
Pulls in a light package history (only back to 0.13.0) for use on the new automated nightly setup for https://apt-test.freedom.press/ . These packages have already been served in prod, with the exception of the 4.4.182 kernels, which have only been published to apt-test to date, to aid in pre-release QA for 0.14.0.
=> Adds historical SD core packages

core/xenial/securedrop-app-code_0.14.0~rc2+xenial_amd64.deb, core/xenial/securedrop-config-0.1.3+0.14.0~rc2-amd64.deb, core/xenial/securedrop-keyring-0.1.3+0.14.0~rc2-amd64.deb, core/xenial/securedrop-ossec-agent-3.0.0+0.14.0~rc2-amd64.deb, core/xenial/securedrop-ossec-server-3.0.0+0.14.0~rc2-amd64.deb
These are packages for SecureDrop 0.14.0~rc2
Recall: we are only committing those packages with new versions, previously committed packages that have changed checksums should not be added again.
Also recall that we should no longer manually deploy deb packages - upon merge these packages _should_ be deployed to apt-test.freedom.press within 15 minutes 🤞
=> SecureDrop core 0.14.0-rc2 packages

core/xenial/tor-geoipdb_0.4.0.5-2~xenial+1_all.deb, core/xenial/tor_0.4.0.5-2~xenial+1_amd64.deb
The upstream tor apt repo no longer serves 0.3.x packages for Xenial, so
we're moving to the 0.4.x series. See the release schedule here:
https://trac.torproject.org/projects/tor/wiki/org/teams/NetworkTeam/CoreTorReleases
The checksums of these files should match exactly what's available in the upstream tor repo: https://deb.torproject.org/torproject.org/pool/main/t/tor/
Meant to be reviewed in tandem with https://github.com/freedomofpress/securedrop/pull/4661
=> Adds tor 0.4.0.5 deb packages

core/xenial/securedrop-app-code_1.0.0~rc1+xenial_amd64.deb, core/xenial/securedrop-config-0.1.3+1.0.0~rc1-amd64.deb, core/xenial/securedrop-keyring-0.1.3+1.0.0~rc1-amd64.deb, core/xenial/securedrop-ossec-agent-3.0.0+1.0.0~rc1-amd64.deb, core/xenial/securedrop-ossec-server-3.0.0+1.0.0~rc1-amd64.deb
Provides SecureDrop core debs build on the 1.0.0-rc1 tag.
=> Add SecureDrop 1.0.0-rc1 debs

core/xenial/tor-geoipdb_0.4.1.5-1~xenial+1_all.deb, core/xenial/tor_0.4.1.5-1~xenial+1_amd64.deb
Updating tor packages after this PR from core was merged: https://github.com/freedomofpress/securedrop/pull/4728
=> update tor packages to 0.4.1.5-1

core/xenial/securedrop-app-code_1.1.0~rc2+xenial_amd64.deb, core/xenial/securedrop-config-0.1.3+1.1.0~rc2-amd64.deb, core/xenial/securedrop-keyring-0.1.3+1.1.0~rc2-amd64.deb, core/xenial/securedrop-ossec-agent-3.0.0+1.1.0~rc2-amd64.deb, core/xenial/securedrop-ossec-server-3.0.0+1.1.0~rc2-amd64.deb
Build logs can be found here: https://github.com/freedomofpress/build-logs/commit/2c9c84947340da1ba3c76c82451ef697df2d7863
=> SecureDrop 1.1.0-rc2

core/xenial/ossec-agent-3.0.0-amd64.deb, core/xenial/ossec-server-3.0.0-amd64.deb, core/xenial/securedrop-app-code_1.1.0~rc3+xenial_amd64.deb, core/xenial/securedrop-config-0.1.3+1.1.0~rc3-amd64.deb, core/xenial/securedrop-keyring-0.1.3+1.1.0~rc3-amd64.deb, core/xenial/securedrop-ossec-agent-3.0.0+1.1.0~rc3-amd64.deb, core/xenial/securedrop-ossec-server-3.0.0+1.1.0~rc3-amd64.deb
Adds SecureDrop core 1.1.0-rc3 deb packages
I used a disposableVM and killed it and I forgot the build logs :(
=> SecureDrop 1.1.0-rc3

core/xenial/ossec-agent-3.0.0-amd64.deb, core/xenial/ossec-server-3.0.0-amd64.deb, core/xenial/securedrop-app-code_1.1.0~rc4+xenial_amd64.deb, core/xenial/securedrop-config-0.1.3+1.1.0~rc4-amd64.deb, core/xenial/securedrop-keyring-0.1.3+1.1.0~rc4-amd64.deb, core/xenial/securedrop-ossec-agent-3.0.0+1.1.0~rc4-amd64.deb, core/xenial/securedrop-ossec-server-3.0.0+1.1.0~rc4-amd64.deb
Also reverted ossec-{agent,server}-3.0.0-amd64.deb to their previous version per our conversation in standup today.
Build logs here: https://github.com/freedomofpress/build-logs/commit/9f633b7022f2c1dca8b5269d33ecdf60104ab55c
=> Add securedrop 1.1.0-rc4 debs

core/xenial/securedrop-app-code_1.1.0~rc5+xenial_amd64.deb, core/xenial/securedrop-config-0.1.3+1.1.0~rc5-amd64.deb, core/xenial/securedrop-keyring-0.1.3+1.1.0~rc5-amd64.deb, core/xenial/securedrop-ossec-agent-3.0.0+1.1.0~rc5-amd64.deb, core/xenial/securedrop-ossec-server-3.0.0+1.1.0~rc5-amd64.deb
- Debs built on https://github.com/freedomofpress/securedrop/tree/1.1.0-rc5
- Logs can be found https://github.com/freedomofpress/build-logs/commit/53526164ecf18bdf31261b45f0a98427f968097c
=> SecureDrop 1.1.0-rc5

workstation/buster/linux-headers-4.14.151-grsec-workstation_4.14.151-grsec-workstation-1_amd64.deb, workstation/buster/linux-image-4.14.151-grsec-workstation_4.14.151-grsec-workstation-1_amd64.deb, workstation/buster/securedrop-workstation-config_0.1.0+buster_all.deb, workstation/buster/securedrop-workstation-config_0.1.1+buster_all.deb, workstation/buster/securedrop-workstation-grsec_4.14.151-1_amd64.deb, workstation/buster/securedrop-workstation-grsec_4.14.151-3+buster_amd64.deb
Provides buster compatibility.
These packages are included in the `buster` channel as they are incompatible with stretch, due to changes in the `CONFIG_GRKERNSEC_PROC_GID` value.
=> Add Buster channel for securedrop-workstation and 4.14.151 kernel images

core/xenial/linux-image-4.14.152-grsec-securedrop_4.14.152-grsec-securedrop-1_amd64.deb, core/xenial/securedrop-grsec-4.14.152-amd64.deb
See https://github.com/freedomofpress/ansible-role-grsecurity-build/pull/51 for config and build changes introduced.
=> Adds 4.14.150 kernel image package and metapackage

core/xenial/linux-image-4.14.154-grsec-securedrop_4.14.154-grsec-securedrop-1_amd64.deb, core/xenial/securedrop-grsec-4.14.154-amd64.deb
Towards https://github.com/freedomofpress/securedrop/issues/4989
Config can be found in https://github.com/freedomofpress/ansible-role-grsecurity-build/pull/52
=> Update SecureDrop grsec kernels to 4.14.154

core/xenial/securedrop-app-code_1.2.0~rc1+xenial_amd64.deb, core/xenial/securedrop-config-0.1.3+1.2.0~rc1-amd64.deb, core/xenial/securedrop-keyring-0.1.3+1.2.0~rc1-amd64.deb, core/xenial/securedrop-ossec-agent-3.0.0+1.2.0~rc1-amd64.deb, core/xenial/securedrop-ossec-server-3.0.0+1.2.0~rc1-amd64.deb
Debian packages for the first release candidate for https://github.com/freedomofpress/securedrop/issues/5004
Build logs are in: https://github.com/freedomofpress/build-logs/blob/master/core/20191120-securedrop-1.2.0-rc1.log (contains hashes of the packages, the commit is signed)
=> securedrop core 1.2.0-rc1 debian packages

workstation/buster/securedrop-client_0.0.10+buster_all.deb, workstation/stretch/securedrop-client_0.0.10+stretch_all.deb
Adds packages for securedrop-client on stretch and buster built using the logic in https://github.com/freedomofpress/securedrop-debian-packaging/pull/89
To build these I set up two AppVMs, one debian 9 and one debian 10 (if you don't have the debian 10 template yet then run `sudo qubes-dom0-update --enablerepo=qubes-templates-itl-testing qubes-template-debian-10` in dom0) and ran the client packaging logic as usual on the corresponding platform.
Build logs:
* Stretch: https://github.com/freedomofpress/build-logs/blob/master/workstation/securedrop-client-stretch-0.0.10-201911201150
* Buster: https://github.com/freedomofpress/build-logs/blob/master/workstation/securedrop-client-buster-0.0.10-201911201129
=> securedrop-client 0.0.10 packages for buster and stretch

workstation/buster/securedrop-export_0.1.2+buster_all.deb
Note: I'm only adding a 0.1.2 package for buster since we already have a stretch package for that release
This uses the packaging changes in: https://github.com/freedomofpress/securedrop-debian-packaging/pull/96
Build log is here: https://github.com/freedomofpress/build-logs/blob/master/workstation/securedrop-export-buster-0.1.2-201911211129
=> securedrop-export 0.1.2 package for buster

workstation/buster/securedrop-workstation-svs-disp_0.1.3+buster_all.deb
Packaging logic merged in https://github.com/freedomofpress/securedrop-debian-packaging/pull/99
=> Adds Buster-compatible securedrop-workstation-svs-disp package

core/xenial/securedrop-app-code_1.2.0~rc2+xenial_amd64.deb, core/xenial/securedrop-config-0.1.3+1.2.0~rc2-amd64.deb, core/xenial/securedrop-keyring-0.1.3+1.2.0~rc2-amd64.deb, core/xenial/securedrop-ossec-agent-3.0.0+1.2.0~rc2-amd64.deb, core/xenial/securedrop-ossec-server-3.0.0+1.2.0~rc2-amd64.deb
=> packages for 1.2.0-rc2

workstation/buster/linux-headers-4.14.158-grsec-workstation_4.14.158-grsec-workstation-1_amd64.deb, workstation/buster/linux-image-4.14.158-grsec-workstation_4.14.158-grsec-workstation-1_amd64.deb, workstation/buster/securedrop-workstation-grsec_4.14.158-1+buster_amd64.deb
Work in progress, will set to ready for review once the PRs in the checklist below have been merged
Towards https://github.com/freedomofpress/securedrop-workstation/issues/234. enables AppArmor support for the workstation kernel
=> Adds 4.14.158 kernels packages with apparmor support

repo/conf/distributions
Adds apt repo configuration files for use with the `reprepro` CLI tool. Includes a distributions config file for all supported platforms:
* xenial
* stretch
* buster
Includes a "SignWith" fingerprint for SD repo test key. Using the test-only SecureDrop repo signing key, with full fingerprint 4ED79CC3362D7D12837046024A3BE4A92211B03C. Reprepro will retrieve that
key from the local keyring (on the apt server) and sign Release files with a detached sig.
Also adds a `Valid-Until` field on the generated Release file, via the `ValidFor` directive in the config presented here.
=> Adds reprepro repository config

workstation/buster/linux-headers-4.14.169-grsec-workstation_4.14.169-grsec-workstation-1_amd64.deb, workstation/buster/linux-image-4.14.169-grsec-workstation_4.14.169-grsec-workstation-1_amd64.deb, workstation/buster/securedrop-workstation-grsec_4.14.169+buster_amd64.deb
As usual, includes both image and header packages for the kernel
sources. Also includes a version bump to the corresponding metapackage,
maintained in the packaging repo [0]
[0] https://github.com/freedomofpress/securedrop-debian-packaging/
The corresponding metapackage change can be found here: https://github.com/freedomofpress/securedrop-debian-packaging/pull/138
=> Add SecureDrop workstation 4.14.169 kernel

core/xenial/securedrop-app-code_1.2.1~rc1+xenial_amd64.deb, core/xenial/securedrop-config-0.1.3+1.2.1~rc1-amd64.deb, core/xenial/securedrop-keyring-0.1.3+1.2.1~rc1-amd64.deb, core/xenial/securedrop-ossec-agent-3.0.0+1.2.1~rc1-amd64.deb, core/xenial/securedrop-ossec-server-3.0.0+1.2.1~rc1-amd64.deb
1.2.1-rc1 packages. Build logs at https://github.com/freedomofpress/build-logs/blob/master/core/20200214-securedrop-1.2.1-rc1
=> SecureDrop core packages for 1.2.1-rc1

core/xenial/securedrop-app-code_1.2.2~rc1+xenial_amd64.deb, core/xenial/securedrop-config-0.1.3+1.2.2~rc1-amd64.deb, core/xenial/securedrop-keyring-0.1.3+1.2.2~rc1-amd64.deb, core/xenial/securedrop-ossec-agent-3.0.0+1.2.2~rc1-amd64.deb, core/xenial/securedrop-ossec-server-3.0.0+1.2.2~rc1-amd64.deb
Towards https://github.com/freedomofpress/securedrop/issues/5156
Build logs available here: https://github.com/freedomofpress/build-logs/commit/7bf8ac4b3b1188df79bc88c338d6a5d03f1a98da
=> SecureDrop 1.2.2-rc1

core/xenial/linux-image-4.14.175-grsec-securedrop_4.14.175-grsec-securedrop-1_amd64.deb, core/xenial/securedrop-grsec-4.14.175-amd64.deb
Towards freedomofpress/securedrop#5111
Config can be found in freedomofpress/ansible-role-grsecurity-build#57
Run `$ dpkg-deb -f core/xenial/securedrop-grsec-4.14.175-amd64.deb Depends`:
=> Update SecureDrop grsec kernels to 4.14.175

core/xenial/tor-geoipdb_0.4.2.7-1~xenial+1_all.deb, core/xenial/tor_0.4.2.7-1~xenial+1_amd64.deb
Ready for review.
Refs https://github.com/freedomofpress/securedrop/issues/5070
See related PR & test plan in https://github.com/freedomofpress/securedrop/pull/5192
Confirm the checksums of the files presented here are identical to what's available in the prod tor repo. 
Additionally, you can run `make fetch-tor-packages` on https://github.com/freedomofpress/securedrop/pull/5192 and confirm those checksums match exactly, as well. The difference with the make target is that gpg verification will be performed on the release file prior to download. 
I did not add build logs, because we don't build these packages, merely mirror them. The "compare checksums" recommendation above satisfies concerns about package integrity.
=> tor: bumps packages to 0.4.2.7-1

core/xenial/ossec-agent-3.6.0-amd64.deb, core/xenial/ossec-server-3.6.0-amd64.deb, core/xenial/securedrop-app-code_1.3.0~rc1+xenial_amd64.deb, core/xenial/securedrop-config-0.1.3+1.3.0~rc1-amd64.deb, core/xenial/securedrop-keyring-0.1.3+1.3.0~rc1-amd64.deb, core/xenial/securedrop-ossec-agent-3.6.0+1.3.0~rc1-amd64.deb, core/xenial/securedrop-ossec-server-3.6.0+1.3.0~rc1-amd64.deb
Towards https://github.com/freedomofpress/securedrop/issues/5205
Build logs available here:https://github.com/freedomofpress/build-logs/commit/d8b6e73fcb416a45dcbf508e0c63c495ecc1b9d4
Debian packages for 1.3.0-rc1. Note that builder security updates check is failing due to out-of-date image - the builder image has since been updated and this test will pass for subsequent release candidates.
=> SecureDrop 1.3.0-rc1

core/xenial/libevent-1.4-2_1.4.14b-stable-0ubuntu1_amd64.deb, core/xenial/libpcre2-8-0_10.21-1_amd64.deb
Adds libevent1.4-2 and libpcre2-8-0 packages to apt-test, as they are not in the Xenial security channel and would otherwise not be available to cron-apt. Packages were retrieved via `apt download` on a Xenial system.
=> added libevent1 and libpcre2 dependencies for ossec 3.6.0

core/xenial/securedrop-app-code_1.3.0~rc2+xenial_amd64.deb, core/xenial/securedrop-config-0.1.3+1.3.0~rc2-amd64.deb, core/xenial/securedrop-keyring-0.1.3+1.3.0~rc2-amd64.deb, core/xenial/securedrop-ossec-agent-3.6.0+1.3.0~rc2-amd64.deb, core/xenial/securedrop-ossec-server-3.6.0+1.3.0~rc2-amd64.deb
Adds deb packages for 1.3.0-rc2
- Build logs: https://github.com/freedomofpress/build-logs/commit/bcdf854e068b7fb9e70d6ce0535db6ed7eef1a9e
Note the builder again needs update, per the build logs (though we did it last week, I propose we do it again prior to release)
=> SecureDrop 1.3.0-rc2

core/xenial/tor-geoipdb_0.4.3.5-1~xenial+1_all.deb, core/xenial/tor_0.4.3.5-1~xenial+1_amd64.deb
Ready for review.
Adds tor-0.4.3.5 deb packages. 
See https://github.com/freedomofpress/securedrop/pull/5292.
Confirm checksums for tor prod packages (https://deb.torproject.org/torproject.org/pool/main/t/tor/tor_0.4.3.5-1_amd64.deb and https://deb.torproject.org/torproject.org/pool/main/t/tor/tor-geoipdb_0.4.3.5-1~xenial+1_all.deb) match the checksums for the pacakges included in this PR. Remember to use `apt` to download the tor prod packages so that the checksums can be verified.
Also, run `make fetch-tor-packages` from the https://github.com/freedomofpress/securedrop/pull/5292 PR branch and confirm checksums of the files downloaded to the build directory match the checksums for the packages included in this PR.
=> add tor-0.4.3.5 packages

workstation/buster/securedrop-keyring_0.1.4+buster_all.deb
Build logs: https://github.com/freedomofpress/build-logs/commit/786eb46672b07b5c635d87a075770b53a0ce3df9
Packaging : https://github.com/freedomofpress/securedrop-debian-packaging/pull/171
Workstation PR: https://github.com/freedomofpress/securedrop-workstation/pull/563
=> Adds securedrop-keyring package to apt-test

core/xenial/securedrop-app-code_1.4.0~rc1+xenial_amd64.deb, core/xenial/securedrop-config-0.1.3+1.4.0~rc1-amd64.deb, core/xenial/securedrop-keyring-0.1.4+1.4.0~rc1-amd64.deb, core/xenial/securedrop-ossec-agent-3.6.0+1.4.0~rc1-amd64.deb, core/xenial/securedrop-ossec-server-3.6.0+1.4.0~rc1-amd64.deb
Towards https://github.com/freedomofpress/securedrop/issues/5289
Build logs available here: https://github.com/freedomofpress/build-logs/commit/dd2aade3c79da34611fd41ab8b18c61b13de3a1d
Debian packages for 1.4.0-rc1. Note that builder security updates check is failing due to out-of-date image. The builder image has not yet been updated accordingly, but should be before rc2.
=> SecureDrop core packages for 1.4.0-rc1

workstation/buster/linux-headers-4.14.186-grsec-workstation_4.14.186-grsec-workstation-1_amd64.deb, workstation/buster/linux-image-4.14.186-grsec-workstation_4.14.186-grsec-workstation-1_amd64.deb, workstation/buster/securedrop-workstation-grsec_4.14.186+buster_amd64.deb
Towards https://github.com/freedomofpress/securedrop-workstation/issues/546
PR includes 4.14.186 workstation kernel packages
=> Added 4.14.186 workstation kernel image, header, and metadata packages

core/xenial/linux-headers-4.14.188-grsec-securedrop_4.14.188-grsec-securedrop-1_amd64.deb, core/xenial/linux-image-4.14.188-grsec-securedrop_4.14.188-grsec-securedrop-1_amd64.deb, core/xenial/securedrop-grsec-4.14.188-amd64.deb
Includes image, headers, and metapackage with updated dependencies.
See https://github.com/freedomofpress/securedrop/pull/5365 for review order of this and related PRs.
=> Adds 4.14.188 server kernels

core/xenial/libevent-1.4-2_1.4.14b-stable-0ubuntu1_amd64.deb, core/xenial/libpcre2-8-0_10.21-1_amd64.deb
Closes https://github.com/freedomofpress/securedrop/issues/5312
Removed upgrade-path dependency packages, `libevent` and `libpcre2`, now that we no longer provide an upgrade path from 1.2.2 with the release of SecureDrop 1.5.0.
Once this PR is merged, reprepro will automatically run and update the apt server metadata (and also automatically sign the release file with the apt-tst key) so that the packages are no longer on our apt-test server. To test this, wait about 10-20 minutes before checking that:
=> remove libevent and libpcre2 packages

core/xenial/tor-geoipdb_0.4.3.6-1~xenial+1_all.deb, core/xenial/tor_0.4.3.6-1~xenial+1_amd64.deb
Adds Tor 0.4.3.6 packages. 
Confirm checksums for https://deb.torproject.org/torproject.org/pool/main/t/tor/tor_0.4.3.6-1~xenial+1_amd64.deb and https://deb.torproject.org/torproject.org/pool/main/t/tor/tor-geoipdb_0.4.3.6-1~xenial+1_all.deb match the checksums for the packages in this PR. 
Also, run `make fetch-tor-packages` from the https://github.com/freedomofpress/securedrop/pull/5374 PR branch (this uses `apt`'s automatic package verification logic) and confirm checksums of the files downloaded to the build directory match the checksums for the packages included in this PR.
=> Add Tor 0.4.3.6 packages

workstation/buster/securedrop-workstation-grsec_4.14.186+buster1_amd64.deb
Adds new metapackage version, see https://github.com/freedomofpress/securedrop-debian-packaging/pull/179 for details. It's important to confirm that this version outranks the prior version so that automatic upgrades will pull it in. See example commands in https://github.com/freedomofpress/securedrop-workstation/issues/590#issuecomment-659574603 and make sure the changes here match. 
I did not submit build logs for this package, since it's dev-only. Will rebuild prior to submitting to prod repo.
=> Adds kernel metapackage v4.14.186+buster1

core/xenial/securedrop-app-code_1.5.0~rc3+xenial_amd64.deb, core/xenial/securedrop-config-0.1.3+1.5.0~rc3-amd64.deb, core/xenial/securedrop-keyring-0.1.4+1.5.0~rc3-amd64.deb, core/xenial/securedrop-ossec-agent-3.6.0+1.5.0~rc3-amd64.deb, core/xenial/securedrop-ossec-server-3.6.0+1.5.0~rc3-amd64.deb
Towards https://github.com/freedomofpress/securedrop/issues/5368
Build logs available here: https://github.com/freedomofpress/build-logs/commit/3d3c3657b12a852260149b1b02c7e8dbb1d720d5
Debian packages for 1.5.0-rc3.
=> Add SecureDrop core 1.5.0-rc3 packages

repo/conf/distributions
Ready for review. Closes #56 
Docs another distribution, Ubuntu Focal 20.04, related to
https://github.com/freedomofpress/securedrop/issues/4768
No packages exist yet, but created the directory in advance.
We don't have any Focal packages yet, so the directory is just a placeholder. Once we start uploading focal packages to this repo, we can monitor for automatic changes to https://apt-test.freedom.press/ and confirm it's working well.
=> Adds Focal channel to apt-test repo

workstation/buster/securedrop-workstation-grsec_4.14.186+buster2_amd64.deb
Includes changes from
https://github.com/freedomofpress/securedrop-debian-packaging/pull/189
=> Adds SDW kernel metapackage 4.14.186+buster2

core/focal/linux-headers-4.14.188-grsec-securedrop_4.14.188-grsec-securedrop-1_amd64.deb, core/focal/linux-image-4.14.175-grsec-securedrop_4.14.175-grsec-securedrop-1_amd64.deb, core/focal/linux-image-4.14.188-grsec-securedrop_4.14.188-grsec-securedrop-1_amd64.deb, core/focal/tor-geoipdb_0.4.3.6-1~focal+1_all.deb, core/focal/tor_0.4.3.6-1~focal+1_amd64.deb
Refs https://github.com/freedomofpress/securedrop-dev-packages-lfs/issues/59
* Adds tor packages for focal, fetched via the new logic in https://github.com/freedomofpress/securedrop/pull/5482
* Adds kernel packages for Focal (image & header)
Reusing the xenial kernel packages for Focal so that we have a baseline to work from. We may end up shipping 5.x kernels soon, but we're still working on building out Focal support.
What's missing here is the "securedrop-grsec" metapackage for Focal. We don't have a unique version string for the metapackage, including a platform such as +xenial or +focal, so we'll have to add some logic to support the package.
Also haven't added the other Focal packages built in the SD repo, so …
=> Adds Focal packages: tor & kernels

core/focal/securedrop-grsec-4.14.188-amd64.deb
Towards https://github.com/freedomofpress/securedrop-dev-packages-lfs/issues/59
In order to provide Focal support, we must ensure that the `securedrop-grsec` metapackage is available via apt, so that the kernel image will be pulled in according to that package's dependencies.
This change copies the exact same metapackage already used for Xenial into the Focal channel.
=> Copies kernel metapackage Xenial -> Focal

core/focal/tor-geoipdb_0.4.4.5-1~focal+1_all.deb, core/focal/tor_0.4.4.5-1~focal+1_amd64.deb, core/xenial/tor-geoipdb_0.4.4.5-1~xenial+1_all.deb, core/xenial/tor_0.4.4.5-1~xenial+1_amd64.deb
This is now tracking Tor's 0.4.4.x series which will be supported until June 2021 and contains performance and security fixes.
See https://github.com/freedomofpress/securedrop/pull/5502
=> Adds Tor 0.4.4.5 packages for Xenial and Focal

core/xenial/securedrop-app-code_1.6.0~rc1+xenial_amd64.deb, core/xenial/securedrop-config-0.1.3+1.6.0~rc1-amd64.deb, core/xenial/securedrop-keyring-0.1.4+1.6.0~rc1-amd64.deb, core/xenial/securedrop-ossec-agent-3.6.0+1.6.0~rc1-amd64.deb, core/xenial/securedrop-ossec-server-3.6.0+1.6.0~rc1-amd64.deb
Provides SecureDrop 1.6.0-rc1 packages, towards https://github.com/freedomofpress/securedrop/issues/5501
Build logs:
https://github.com/freedomofpress/build-logs/commit/3666cc4378e922548754f09e511f7645ef28088a
=> Adds debs for SecureDrop 1.6.0-rc1

core/xenial/securedrop-app-code_1.6.0~rc2+xenial_amd64.deb, core/xenial/securedrop-config-0.1.3+1.6.0~rc2-amd64.deb, core/xenial/securedrop-keyring-0.1.4+1.6.0~rc2-amd64.deb, core/xenial/securedrop-ossec-agent-3.6.0+1.6.0~rc2-amd64.deb, core/xenial/securedrop-ossec-server-3.6.0+1.6.0~rc2-amd64.deb
Towards https://github.com/freedomofpress/securedrop/issues/5501
=> Adds deb packages for SecureDrop 1.6.0-rc2

repo/conf/distributions, workstation/template-consolidation/securedrop-proxy_0.3.1+buster_all.deb, workstation/template-consolidation/securedrop-workstation-viewer_0.1.0+buster_all.deb, workstation/template-consolidation/securedrop-workstation-viewer_0.1.1+buster_all.deb
Using a dedicated "component" so that we can isolate ongoing development
specifically on template consolidation work [0] so that we can evaluate
upgrade behavior. While it's frankly acceptable to break "apt-test"
packages temporarily, we need the ability to test before/after states to
evaluate behavior during upgrades. Thus the separate component.
Requires updates to the CD logic that runs on apt-test.
Towards https://github.com/freedomofpress/securedrop-workstation/issues/471
Contains newly built packages based on changes in https://github.com/freedomofpress/securedrop-debian-packaging/pull/198
Confirming the above, since apt-test is currently tracking this feature branch, is essentially verifying the following apt cache output:
```
securedrop-proxy:
Installed: (none) …
```
=> Add template-consolidation component for buster 

workstation/template-consolidation/securedrop-export_0.2.4+buster_all.deb
Removes mimetype associations, incorporating changes from PR
https://github.com/freedomofpress/securedrop-export/pull/65
Not including build logs since we'll rebuild all of the packages in the "template-consolidation" channel after testing and review. Part of the epic https://github.com/freedomofpress/securedrop-workstation/issues/471
=> Adds securedrop-export 0.2.4 rc pkg

workstation/template-consolidation/securedrop-proxy_0.3.1+buster_all.deb
Incorporated newer build dependencies, see discussion in
https://github.com/freedomofpress/securedrop-proxy/pull/79#pullrequestreview-511972118
No build logs because specific to template consolidation (https://github.com/freedomofpress/securedrop-workstation/issues/471). Visual review is sufficient.
=> Rebuilds proxy for template-consolidation

workstation/template-consolidation/securedrop-client_0.2.2+buster_all.deb
Removes mimetypes from the securedrop-client package, given that they're now provided in
`securedrop-workstation-config`. See corresponding changes in:
* https://github.com/freedomofpress/securedrop-client/pull/1160
* https://github.com/freedomofpress/securedrop-debian-packaging/pull/198
No build logs because specific to template consolidation (freedomofpress/securedrop-workstation#471). Visual review is sufficient
=> Rebuilds client for template-consolidation

workstation/template-consolidation/securedrop-workstation-config_0.1.5+buster_all.deb
Adjusts mimetypes handling, consolidating into a single package as much
as possible. See:
https://github.com/freedomofpress/securedrop-debian-packaging/pull/198
No build logs because specific to template consolidation (freedomofpress/securedrop-workstation#471). Visual review is sufficient
=> Rebuilds sdw-config for template-consolidation

workstation/buster/securedrop-workstation-config_0.1.5+buster_all.deb, workstation/buster/securedrop-workstation-viewer_0.1.1+buster_all.deb, workstation/template-consolidation/securedrop-client_0.2.2+buster_all.deb, workstation/template-consolidation/securedrop-export_0.2.4+buster_all.deb, workstation/template-consolidation/securedrop-proxy_0.3.1+buster_all.deb, workstation/template-consolidation/securedrop-workstation-config_0.1.5+buster_all.deb, workstation/template-consolidation/securedrop-workstation-viewer_0.1.1+buster_all.deb
Rebuilds two (2) packages after merge of
Also removes template-consolidation testing debs. These debs were published to a dedicated "template-consolidation" channel to aid in testing. We're now proceeding with testing against apt-test main, where the nightly packages will be available. Removing these since several had their versions bump, and they'd supersede the nightlies.
Note: we haven't tagged the packaging repo yet, so the build logs below don't include verification of sigs for component code. 
- https://github.com/freedomofpress/build-logs/commit/62d228fdfa282127ea42c59129fb9a904e49efaa
- https://github.com/freedomofpress/build-logs/commit/ff73426a121a371681a9ee1a937c8db35cdc4aa5
=> Rebuilds packages for template-consolidation

workstation/buster/securedrop-client_0.3.0-dev-20201105-368730+buster_all.deb
Adds securedrop-client package to include data migration in https://github.com/freedomofpress/securedrop-client/pull/1184 
Build logs have been committed to [build-logs](https://github.com/freedomofpress/build-logs/blob/main/workstation/securedrop-client-0.3.0-dev-20201105).
=> add client deb for workstation 0.5.0 release qa

workstation/buster/securedrop-workstation-grsec_4.14.186+buster3_amd64.deb
=> Add workstation kernel metapkg 4.14.186+buster3

workstation/buster/securedrop-workstation-grsec_4.14.186+buster3_amd64.deb
Rebuilds the `securedrop-workstation-grsec` metapackage, based on a new commit adding a `Pre-Depends` field.
=> Rebuild workstation kernel metapkg 4.14.186+buster3

core/focal/securedrop-grsec-4.14.188+focal-amd64.deb
Built after merge of [0], build logs at [1]. Will unblock testing, via apt-test repos, of Focal support on hardware. 
[0] https://github.com/freedomofpress/securedrop/pull/5691
[1] https://github.com/freedomofpress/build-logs/commit/06916a44cabb62e38567908898bfd567cd0a70b8
=> Adds securedrop-grsec pkg for Focal

core/xenial/securedrop-app-code_1.7.0~rc1+xenial_amd64.deb, core/xenial/securedrop-config-0.1.3+1.7.0~rc1-amd64.deb, core/xenial/securedrop-keyring-0.1.4+1.7.0~rc1-amd64.deb, core/xenial/securedrop-ossec-agent-3.6.0+1.7.0~rc1-amd64.deb, core/xenial/securedrop-ossec-server-3.6.0+1.7.0~rc1-amd64.deb
Adds SecureDrop 1.7.0-rc1 packages, towards freedomofpress/securedrop#5689
Build logs can be found: https://github.com/freedomofpress/build-logs/commit/f5dc8453a34887aabd11b917c18ebd3198161093
=> Add debs for SecureDrop 1.7.0-rc1

core/xenial/securedrop-app-code_1.7.0~rc2+xenial_amd64.deb, core/xenial/securedrop-config-0.1.3+1.7.0~rc2-amd64.deb, core/xenial/securedrop-keyring-0.1.4+1.7.0~rc2-amd64.deb, core/xenial/securedrop-ossec-agent-3.6.0+1.7.0~rc2-amd64.deb, core/xenial/securedrop-ossec-server-3.6.0+1.7.0~rc2-amd64.deb
Build logs: https://github.com/freedomofpress/build-logs/commit/f48a50c1e99c74d19dad5370b50012830fa315f7
=> Adds packages for securedrop 1.7.0-rc2

core/xenial/securedrop-app-code_1.7.0~rc4+xenial_amd64.deb, core/xenial/securedrop-config-0.1.3+1.7.0~rc4-amd64.deb, core/xenial/securedrop-keyring-0.1.4+1.7.0~rc4-amd64.deb, core/xenial/securedrop-ossec-agent-3.6.0+1.7.0~rc4-amd64.deb, core/xenial/securedrop-ossec-server-3.6.0+1.7.0~rc4-amd64.deb
Adds deb packages for SecureDrop 1.7.0-rc4, based on https://github.com/freedomofpress/securedrop/pull/5738. Only adding Xenial packages, skipping Focal due to https://github.com/freedomofpress/securedrop-dev-packages-lfs/issues/85.
=> SecureDrop 1.7.0-rc4 (Xenial)

core/focal/linux-headers-5.4.88-grsec-securedrop_5.4.88-grsec-securedrop-1_amd64.deb, core/focal/linux-image-5.4.88-grsec-securedrop_5.4.88-grsec-securedrop-1_amd64.deb
Towards https://github.com/freedomofpress/securedrop/issues/5479. This adds new 5.4.x kernels, built for SecureDrop servers, with the pre-existing patches already present for older model hardware support.
These do *not* include additional patches for e.g. NUC10 support. Will rebuild once those are ready.
Uses new logic in https://github.com/conorsch/kernel-builder/ , which also permits saving build logs.
=> Adds 5.4.88 kernels for Focal

core/focal/securedrop-grsec-5.4.88+focal-amd64.deb
Ready for review, should only be merged once https://github.com/freedomofpress/securedrop/pull/5772 is approved.
Provides an updated metapackage for Ubuntu Focal that will install a 5.4.88 kernel, see https://github.com/freedomofpress/securedrop/pull/5772 . The kernel image was already merged in #81.
=> Adds securedrop-grsec 5.4.88 package for Ubuntu Focal

core/focal/securedrop-config-0.1.4+1.8.0~rc1+focal-amd64.deb
Provides a focal-only update to the securedrop-config package, which contains the files required to configure unattended-upgrades. This includes the changes introduced in https://github.com/freedomofpress/securedrop/pull/5684
=> Adds securedrop-config 0.1.4 package for focal

core/focal/linux-headers-5.4.97-grsec-securedrop_5.4.97-grsec-securedrop-1_amd64.deb, core/focal/linux-image-5.4.97-grsec-securedrop_5.4.97-grsec-securedrop-1_amd64.deb
=> Adds 5.4.97 kernel for Focal

core/focal/tor-geoipdb_0.4.5.6-1~focal+1_all.deb, core/focal/tor_0.4.5.6-1~focal+1_amd64.deb, core/xenial/tor-geoipdb_0.4.5.6-1~xenial+1_all.deb, core/xenial/tor_0.4.5.6-1~xenial+1_amd64.deb
Provides Tor 0.4.5.6  packages for xenial and focal
Build logs; https://github.com/freedomofpress/build-logs/commit/5bbc480f8791abe117d8044e2098a6925924a5aa
=> Adds Tor 0.4.5.6 packages for xenial and focal

core/focal/securedrop-app-code_1.8.0~rc1+focal_amd64.deb, core/focal/securedrop-config-0.1.4+1.8.0~rc1+focal-amd64.deb, core/focal/securedrop-grsec-5.4.97+focal-amd64.deb, core/focal/securedrop-keyring-0.1.4+1.8.0~rc1+focal-amd64.deb, core/focal/securedrop-ossec-agent-3.6.0+1.8.0~rc1+focal-amd64.deb, core/focal/securedrop-ossec-server-3.6.0+1.8.0~rc1+focal-amd64.deb, core/xenial/securedrop-app-code_1.8.0~rc1+xenial_amd64.deb, core/xenial/securedrop-config-0.1.4+1.8.0~rc1+xenial-amd64.deb, core/xenial/securedrop-keyring-0.1.4+1.8.0~rc1+xenial-amd64.deb, core/xenial/securedrop-ossec-agent-3.6.0+1.8.0~rc1+xenial-amd64.deb, core/xenial/securedrop-ossec-server-3.6.0+1.8.0~rc1+xenial-amd64.deb
=> SecureDrop 1.8.0-rc1

core/focal/securedrop-app-code_1.8.0~rc2+focal_amd64.deb, core/focal/securedrop-config-0.1.4+1.8.0~rc2+focal-amd64.deb, core/focal/securedrop-keyring-0.1.4+1.8.0~rc2+focal-amd64.deb, core/focal/securedrop-ossec-agent-3.6.0+1.8.0~rc2+focal-amd64.deb, core/focal/securedrop-ossec-server-3.6.0+1.8.0~rc2+focal-amd64.deb, core/xenial/securedrop-app-code_1.8.0~rc2+xenial_amd64.deb, core/xenial/securedrop-config-0.1.4+1.8.0~rc2+xenial-amd64.deb, core/xenial/securedrop-keyring-0.1.4+1.8.0~rc2+xenial-amd64.deb, core/xenial/securedrop-ossec-agent-3.6.0+1.8.0~rc2+xenial-amd64.deb, core/xenial/securedrop-ossec-server-3.6.0+1.8.0~rc2+xenial-amd64.deb
Build logs: https://github.com/freedomofpress/build-logs/commit/33b894ba6d1cdd45f2381f422f45a119436cccad
=> Adds debs for SecureDrop 1.8.0-rc2

core/focal/securedrop-app-code_1.8.0~rc3+focal_amd64.deb, core/focal/securedrop-config-0.1.4+1.8.0~rc3+focal-amd64.deb, core/focal/securedrop-keyring-0.1.4+1.8.0~rc3+focal-amd64.deb, core/focal/securedrop-ossec-agent-3.6.0+1.8.0~rc3+focal-amd64.deb, core/focal/securedrop-ossec-server-3.6.0+1.8.0~rc3+focal-amd64.deb, core/xenial/securedrop-app-code_1.8.0~rc3+xenial_amd64.deb, core/xenial/securedrop-config-0.1.4+1.8.0~rc3+xenial-amd64.deb, core/xenial/securedrop-keyring-0.1.4+1.8.0~rc3+xenial-amd64.deb, core/xenial/securedrop-ossec-agent-3.6.0+1.8.0~rc3+xenial-amd64.deb, core/xenial/securedrop-ossec-server-3.6.0+1.8.0~rc3+xenial-amd64.deb
=> SecureDrop 1.8.0-rc3

core/focal/securedrop-app-code_1.8.0~rc4+focal_amd64.deb, core/focal/securedrop-config-0.1.4+1.8.0~rc4+focal-amd64.deb, core/focal/securedrop-keyring-0.1.4+1.8.0~rc4+focal-amd64.deb, core/focal/securedrop-ossec-agent-3.6.0+1.8.0~rc4+focal-amd64.deb, core/focal/securedrop-ossec-server-3.6.0+1.8.0~rc4+focal-amd64.deb, core/xenial/securedrop-app-code_1.8.0~rc4+xenial_amd64.deb, core/xenial/securedrop-config-0.1.4+1.8.0~rc4+xenial-amd64.deb, core/xenial/securedrop-keyring-0.1.4+1.8.0~rc4+xenial-amd64.deb, core/xenial/securedrop-ossec-agent-3.6.0+1.8.0~rc4+xenial-amd64.deb, core/xenial/securedrop-ossec-server-3.6.0+1.8.0~rc4+xenial-amd64.deb
Builds 1.8.0~rc4 debs, for both Xenial & Focal.
=> Adds pkgs for SecureDrop 1.8.0-rc4

workstation/buster/securedrop-workstation-config_0.1.6+buster_all.deb
=> Adds securedrop-workstation-config 0.1.6

core/focal/securedrop-app-code_1.8.0~rc5+focal_amd64.deb, core/focal/securedrop-config-0.1.4+1.8.0~rc5+focal-amd64.deb, core/focal/securedrop-keyring-0.1.4+1.8.0~rc5+focal-amd64.deb, core/focal/securedrop-ossec-agent-3.6.0+1.8.0~rc5+focal-amd64.deb, core/focal/securedrop-ossec-server-3.6.0+1.8.0~rc5+focal-amd64.deb
no-op RC for upgrade testing purposes. Only versions and changelogs are updated.
=> SecureDrop 1.8.0-rc5

core/focal/tor-geoipdb_0.4.4.5-1~focal+1_all.deb, core/focal/tor-geoipdb_0.4.4.6-1~focal+1_all.deb, core/focal/tor-geoipdb_0.4.5.7-1~focal+1_all.deb, core/focal/tor_0.4.4.5-1~focal+1_amd64.deb, core/focal/tor_0.4.4.6-1~focal+1_amd64.deb, core/focal/tor_0.4.5.7-1~focal+1_amd64.deb, core/xenial/tor-geoipdb_0.4.4.5-1~xenial+1_all.deb, core/xenial/tor-geoipdb_0.4.4.6-1~xenial+1_all.deb, core/xenial/tor-geoipdb_0.4.5.7-1~xenial+1_all.deb, core/xenial/tor_0.4.4.5-1~xenial+1_amd64.deb, core/xenial/tor_0.4.4.6-1~xenial+1_amd64.deb, core/xenial/tor_0.4.5.7-1~xenial+1_amd64.deb
=> Added Tor 0.4.5.7 packages, removed Tor 0.4.4.* packages.

core/focal/securedrop-app-code_1.8.1~rc1+focal_amd64.deb, core/focal/securedrop-config-0.1.4+1.8.1~rc1+focal-amd64.deb, core/focal/securedrop-keyring-0.1.4+1.8.1~rc1+focal-amd64.deb, core/focal/securedrop-ossec-agent-3.6.0+1.8.1~rc1+focal-amd64.deb, core/focal/securedrop-ossec-server-3.6.0+1.8.1~rc1+focal-amd64.deb, core/xenial/securedrop-app-code_1.8.1~rc1+xenial_amd64.deb, core/xenial/securedrop-config-0.1.4+1.8.1~rc1+xenial-amd64.deb, core/xenial/securedrop-keyring-0.1.4+1.8.1~rc1+xenial-amd64.deb, core/xenial/securedrop-ossec-agent-3.6.0+1.8.1~rc1+xenial-amd64.deb, core/xenial/securedrop-ossec-server-3.6.0+1.8.1~rc1+xenial-amd64.deb
=> Adds debs for SecureDrop 1.8.1-rc1

core/focal/securedrop-app-code_1.8.2~rc3+focal_amd64.deb, core/focal/securedrop-config-0.1.4+1.8.2~rc3+focal-amd64.deb, core/focal/securedrop-keyring-0.1.5+1.8.2~rc3+focal-amd64.deb, core/focal/securedrop-ossec-agent-3.6.0+1.8.2~rc3+focal-amd64.deb, core/focal/securedrop-ossec-server-3.6.0+1.8.2~rc3+focal-amd64.deb
=> Adds SecureDrop 1.8.2-rc3 packages

workstation/buster/securedrop-keyring_0.1.5+buster_all.deb
=> Adds securedrop-keyring 0.1.5

core/focal/tor-geoipdb_0.4.5.6-1~focal+1_all.deb, core/focal/tor-geoipdb_0.4.5.8-1~focal+1_all.deb, core/focal/tor_0.4.5.6-1~focal+1_amd64.deb, core/focal/tor_0.4.5.8-1~focal+1_amd64.deb
=> Added Tor 0.4.5.8 packages

core/focal/securedrop-app-code_2.0.0~rc1+focal_amd64.deb, core/focal/securedrop-config-0.1.4+2.0.0~rc1+focal-amd64.deb, core/focal/securedrop-keyring-0.1.5+2.0.0~rc1+focal-amd64.deb, core/focal/securedrop-ossec-agent-3.6.0+2.0.0~rc1+focal-amd64.deb, core/focal/securedrop-ossec-server-3.6.0+2.0.0~rc1+focal-amd64.deb
=> Adds packages for SecureDrop 2.0.0-rc1

core/focal/securedrop-app-code_2.0.0~rc2+focal_amd64.deb, core/focal/securedrop-config-0.1.4+2.0.0~rc2+focal-amd64.deb, core/focal/securedrop-keyring-0.1.5+2.0.0~rc2+focal-amd64.deb, core/focal/securedrop-ossec-agent-3.6.0+2.0.0~rc2+focal-amd64.deb, core/focal/securedrop-ossec-server-3.6.0+2.0.0~rc2+focal-amd64.deb
=> Adds packages for SecureDrop 2.0.0-rc2

core/focal/securedrop-app-code_2.0.0~rc3+focal_amd64.deb, core/focal/securedrop-config-0.1.4+2.0.0~rc3+focal-amd64.deb, core/focal/securedrop-keyring-0.1.5+2.0.0~rc3+focal-amd64.deb, core/focal/securedrop-ossec-agent-3.6.0+2.0.0~rc3+focal-amd64.deb, core/focal/securedrop-ossec-server-3.6.0+2.0.0~rc3+focal-amd64.deb
Adds packages for SecureDrop 2.0.0-rc3
=> Adds packages for SecureDrop 2.0.0-rc3

core/focal/securedrop-app-code_2.0.0~rc4+focal_amd64.deb, core/focal/securedrop-config-0.1.4+2.0.0~rc4+focal-amd64.deb, core/focal/securedrop-keyring-0.1.5+2.0.0~rc4+focal-amd64.deb, core/focal/securedrop-ossec-agent-3.6.0+2.0.0~rc4+focal-amd64.deb, core/focal/securedrop-ossec-server-3.6.0+2.0.0~rc4+focal-amd64.deb
=> SecureDrop 2.0.0-rc4

core/focal/securedrop-app-code_2.0.0~rc5+focal_amd64.deb, core/focal/securedrop-config-0.1.4+2.0.0~rc5+focal-amd64.deb, core/focal/securedrop-keyring-0.1.5+2.0.0~rc5+focal-amd64.deb, core/focal/securedrop-ossec-agent-3.6.0+2.0.0~rc5+focal-amd64.deb, core/focal/securedrop-ossec-server-3.6.0+2.0.0~rc5+focal-amd64.deb
Adds SecureDrop 2.0.0-rc5 packages.
=> SecureDrop 2.0.0-rc5

workstation/buster/linux-headers-4.14.240-grsec-workstation_4.14.240-grsec-workstation-1_amd64.deb, workstation/buster/linux-image-4.14.240-grsec-workstation_4.14.240-grsec-workstation-1_amd64.deb, workstation/buster/securedrop-workstation-grsec_4.14.240+buster_amd64.deb
Includes metapackage [0] and kernel images.
[0] https://github.com/freedomofpress/securedrop-debian-packaging/pull/255
- Metapackage: https://github.com/freedomofpress/build-logs/commit/668a48daac0a6100058fab9fbcf7f460d4ab6ab7
- Kernel: https://github.com/freedomofpress/build-logs/commit/1fda41b2104fe4a3fde2edc4be873c6806be7fda
I haven't actually tested these changes yet, but I'm comfortable doing so post-merge to apt-test, and will follow up with further changes only if required.
=> Workstation kernel 4.14.240

workstation/buster/securedrop-workstation-grsec_4.14.240+buster_amd64.deb
Follow-up to #116 
Omitted the version string bump in the control file, so the new packages
weren't pulled in, but postinst tried to operate on the dkms modules,
resulting in an install failure.
=> Rebuilds metapackage for workstation kernel

core/focal/linux-headers-5.4.136-grsec-securedrop_5.4.136-grsec-securedrop-1_amd64.deb, core/focal/linux-image-5.4.136-grsec-securedrop_5.4.136-grsec-securedrop-1_amd64.deb
=> Adds 5.4.136-grsec kernel

core/focal/securedrop-app-code_2.0.2~rc1+focal_amd64.deb, core/focal/securedrop-config-0.1.4+2.0.2~rc1+focal-amd64.deb, core/focal/securedrop-grsec-5.4.136+focal-amd64.deb, core/focal/securedrop-keyring-0.1.5+2.0.2~rc1+focal-amd64.deb, core/focal/securedrop-ossec-agent-3.6.0+2.0.2~rc1+focal-amd64.deb, core/focal/securedrop-ossec-server-3.6.0+2.0.2~rc1+focal-amd64.deb
=> Add securedrop 2.0.2-rc1 packages

workstation/buster/linux-headers-4.14.241-grsec-workstation_4.14.241-grsec-workstation-1_amd64.deb, workstation/buster/linux-image-4.14.241-grsec-workstation_4.14.241-grsec-workstation-1_amd64.deb, workstation/buster/securedrop-workstation-grsec_4.14.241+buster_amd64.deb
=> Workstation kernel 4.14.241

core/focal/tor-geoipdb_0.4.5.10-1~focal+1_all.deb, core/focal/tor-geoipdb_0.4.5.7-1~focal+1_all.deb, core/focal/tor_0.4.5.10-1~focal+1_amd64.deb, core/focal/tor_0.4.5.7-1~focal+1_amd64.deb
=> Added Tor 0.4.5.10 packages

core/focal/securedrop-app-code_2.1.0~rc1+focal_amd64.deb, core/focal/securedrop-config-0.1.4+2.1.0~rc1+focal-amd64.deb, core/focal/securedrop-keyring-0.1.5+2.1.0~rc1+focal-amd64.deb, core/focal/securedrop-ossec-agent-3.6.0+2.1.0~rc1+focal-amd64.deb, core/focal/securedrop-ossec-server-3.6.0+2.1.0~rc1+focal-amd64.deb
Builds 2.1.0-rc1 debs, towards https://github.com/freedomofpress/securedrop/issues/6103
=> Add debs for SecureDrop 2.1.0-rc1

core/focal/securedrop-app-code_2.1.0~rc2+focal_amd64.deb, core/focal/securedrop-config-0.1.4+2.1.0~rc2+focal-amd64.deb, core/focal/securedrop-keyring-0.1.5+2.1.0~rc2+focal-amd64.deb, core/focal/securedrop-ossec-agent-3.6.0+2.1.0~rc2+focal-amd64.deb, core/focal/securedrop-ossec-server-3.6.0+2.1.0~rc2+focal-amd64.deb
=> Add SecureDrop 2.1.0~rc2 debs

core/focal/tor-geoipdb_0.4.5.8-1~focal+1_all.deb, core/focal/tor-geoipdb_0.4.6.8-1~focal+1_all.deb, core/focal/tor_0.4.5.8-1~focal+1_amd64.deb, core/focal/tor_0.4.6.8-1~focal+1_amd64.deb
=> Added Tor 0.4.6.8 packages, removed 0.4.5.8 packages

core/focal/tor-geoipdb_0.4.6.8-1~focal+1_all.deb, core/focal/tor-geoipdb_0.4.6.9-1~focal+1_all.deb, core/focal/tor_0.4.6.8-1~focal+1_amd64.deb, core/focal/tor_0.4.6.9-1~focal+1_amd64.deb
Removes 0.4.6.8 packages, adds 0.4.6.9 packages.
=> Updated to 0.4.6.9 Tor packages

workstation/buster/securedrop-client_0.6.0-rc1+buster_all.deb
=> securedrop-client 0.6.0-rc1

core/focal/linux-headers-5.15.18-grsec-securedrop_5.15.18-grsec-securedrop-1_amd64.deb, core/focal/linux-image-5.15.18-grsec-securedrop_5.15.18-grsec-securedrop-1_amd64.deb
=> Adds 5.15.18 grsec server kernels

workstation/buster/securedrop-client_0.6.0-rc1-dev-20220127-060610+buster_all.deb, workstation/buster/securedrop-client_0.6.0-rc1-dev-20220128-060543+buster_all.deb, workstation/buster/securedrop-client_0.6.0-rc1-dev-20220129-060601+buster_all.deb, workstation/buster/securedrop-client_0.6.0-rc1-dev-20220130-060550+buster_all.deb, workstation/buster/securedrop-client_0.6.0-rc1-dev-20220131-060613+buster_all.deb
We forgot to pause the nightlies last week, prior to preparing an rc1
package, so the nightly packages are winning on dpkg version compare:
```
dpkg --compare-versions 0.6.0-rc1+buster gt 0.6.0-rc1-dev-20220127-060610+buster
echo $?
1
```
Removing them to resolve the conflict, and ensure only 0.6.0-rc1 is
served from apt-test.
See testing details below. Our "just pull from git" logic on apt-test isn't smart enough to handle package removals intelligently, so old packages can still appear in the HTML webview—but reprepro only honors the most recent available version, and the repo metadata was correct, so 0.6.0-rc1 was being offered, as expected.
=> Remove client 0.6.0 nightlies

workstation/buster/securedrop-client_0.6.0-rc2+buster_all.deb
=> securedrop-client 0.6.0-rc2

core/focal/securedrop-app-code_2.2.0~rc1+focal_amd64.deb, core/focal/securedrop-config-0.1.4+2.2.0~rc1+focal-amd64.deb, core/focal/securedrop-grsec-5.15.18+focal-amd64.deb, core/focal/securedrop-keyring-0.1.5+2.2.0~rc1+focal-amd64.deb, core/focal/securedrop-ossec-agent-3.6.0+2.2.0~rc1+focal-amd64.deb, core/focal/securedrop-ossec-server-3.6.0+2.2.0~rc1+focal-amd64.deb
=> Add debs for SecureDrop 2.2.0-rc1

workstation/buster/securedrop-client_0.6.0-rc3+buster_all.deb
=> Add securedrop-client 0.6.0-rc3

core/focal/securedrop-app-code_2.2.0~rc2+focal_amd64.deb, core/focal/securedrop-config-0.1.4+2.2.0~rc2+focal-amd64.deb, core/focal/securedrop-keyring-0.1.5+2.2.0~rc2+focal-amd64.deb, core/focal/securedrop-ossec-agent-3.6.0+2.2.0~rc2+focal-amd64.deb, core/focal/securedrop-ossec-server-3.6.0+2.2.0~rc2+focal-amd64.deb
=> Add SecureDrop 2.2.0-rc2 packages

workstation/buster/securedrop-client_0.6.0-rc4+buster_all.deb
=> Add securedrop-client 0.6.0-rc4

core/focal/securedrop-app-code_2.2.0~rc3+focal_amd64.deb, core/focal/securedrop-config-0.1.4+2.2.0~rc3+focal-amd64.deb, core/focal/securedrop-grsec-5.15.18+focal-amd64.deb, core/focal/securedrop-keyring-0.1.5+2.2.0~rc3+focal-amd64.deb, core/focal/securedrop-ossec-agent-3.6.0+2.2.0~rc3+focal-amd64.deb, core/focal/securedrop-ossec-server-3.6.0+2.2.0~rc3+focal-amd64.deb
After merge, let's make sure to monitor for the `securedrop-grsec` package being updated. The apt-test server logic may not be smart enough to clobber the package in-place, since there's no version bump.
=> Add SecureDrop 2.2.0-rc3 debs

core/focal/securedrop-app-code_2.2.1~rc1+focal_amd64.deb, core/focal/securedrop-config-0.1.4+2.2.1~rc1+focal-amd64.deb, core/focal/securedrop-grsec-5.15.26+focal-amd64.deb, core/focal/securedrop-keyring-0.1.5+2.2.1~rc1+focal-amd64.deb, core/focal/securedrop-ossec-agent-3.6.0+2.2.1~rc1+focal-amd64.deb, core/focal/securedrop-ossec-server-3.6.0+2.2.1~rc1+focal-amd64.deb
=> Add 2.2.1-rc1 and securedrop-grsec-5.15.26 packages

core/focal/securedrop-app-code_2.3.1~rc1+focal_amd64.deb, core/focal/securedrop-config-0.1.4+2.3.1~rc1+focal-amd64.deb, core/focal/securedrop-keyring-0.1.5+2.3.1~rc1+focal-amd64.deb, core/focal/securedrop-ossec-agent-3.6.0+2.3.1~rc1+focal-amd64.deb, core/focal/securedrop-ossec-server-3.6.0+2.3.1~rc1+focal-amd64.deb
Add packages for 2.3.1-rc1 hotfix release testing
=> Add SecureDrop 2.3.1-rc1 debs

workstation/buster/securedrop-client_0.7.0-rc1+buster_all.deb
=> Add securedrop-client-0.7.0-rc1

workstation/buster/securedrop-client_0.7.0-rc2+buster_all.deb
Towards https://github.com/freedomofpress/securedrop-client/issues/1465
=> Add securedrop-client 0.7.0-rc2

workstation/buster/securedrop-client_0.7.0-rc3+buster_all.deb
Towards https://github.com/freedomofpress/securedrop-client/issues/1465
- Cross-link to https://github.com/freedomofpress/securedrop-debian-packaging/pull/303
- Build logs have been committed to https://github.com/freedomofpress/build-logs/commit/d2b03e0e74ed8b2a510600ce0e0a7b9703b0b25a
=> Add securedrop-client 0.7.0-rc3

workstation/buster/securedrop-export_0.2.6+buster_all.deb, workstation/buster/securedrop-proxy_0.3.1+buster_all.deb, workstation/buster/securedrop-workstation-svs-disp_0.2.2+buster_all.deb
Copied the deb files from `securedrop-debian-packages-lfs`.
Fixes #149
=> Update workstation packages to their recent stable versions

workstation/buster/securedrop-workstation-config_0.1.7+buster_all.deb
Towards https://github.com/freedomofpress/securedrop-debian-packaging/issues/312
Once this PR is merged and on `apt-test`, follow test plan in https://github.com/freedomofpress/securedrop-debian-packaging/issues/312
=> add securedrop-workstation-config 0.1.7

core/focal/securedrop-app-code_2.3.2~rc1+focal_amd64.deb, core/focal/securedrop-config-0.1.4+2.3.2~rc1+focal-amd64.deb, core/focal/securedrop-keyring-0.1.5+2.3.2~rc1+focal-amd64.deb, core/focal/securedrop-ossec-agent-3.6.0+2.3.2~rc1+focal-amd64.deb, core/focal/securedrop-ossec-server-3.6.0+2.3.2~rc1+focal-amd64.deb
=> added SecureDrop 2.3.2-rc1 debs

core/focal/securedrop-app-code_2.4.0~rc1+focal_amd64.deb, core/focal/securedrop-config-0.1.4+2.4.0~rc1+focal-amd64.deb, core/focal/securedrop-keyring-0.1.5+2.4.0~rc1+focal-amd64.deb, core/focal/securedrop-ossec-agent-3.6.0+2.4.0~rc1+focal-amd64.deb, core/focal/securedrop-ossec-server-3.6.0+2.4.0~rc1+focal-amd64.deb
=> added securedrop 2.4.0-rc1 packages

core/focal/securedrop-app-code_2.4.0~rc2+focal_amd64.deb, core/focal/securedrop-config-0.1.4+2.4.0~rc2+focal-amd64.deb, core/focal/securedrop-keyring-0.1.6+2.4.0~rc2+focal-amd64.deb, core/focal/securedrop-ossec-agent-3.6.0+2.4.0~rc2+focal-amd64.deb, core/focal/securedrop-ossec-server-3.6.0+2.4.0~rc2+focal-amd64.deb
=> Added securedrop 2.4.0-rc2 packages

workstation/bullseye/securedrop-keyring_0.1.6+bullseye_all.deb, workstation/buster/securedrop-keyring_0.1.6+buster_all.deb
Towards https://github.com/freedomofpress/securedrop-debian-packaging/issues/319
=> add securedrop-keyring 0.1.6 packages for buster and bullseye

workstation/bullseye/securedrop-workstation-config_0.1.7+bullseye_all.deb
Add securedrop-workstation-config 0.1.7 for bullseye.
=> add securedrop-workstation-config 0.1.7 package for bullseye

workstation/bullseye/xpp_1.5-cvs20081009-4_amd64.deb
Works towards freedomofpress/securedrop-debian-packaging#343 by adding buster's last `xpp`, which installs and runs on bullseye.
=> host buster's `xpp` for bullseye

workstation/bullseye-nightlies/xpp_1.5-cvs20081009-4_amd64.deb
Copied https://apt-test.freedom.press/pool/main/x/xpp/ into nightlies so that we can test on Qubes 4.1 using `make dev`.
=> copy xpp package to nightlies

workstation/securedrop-export_0.3.0+bullseye_all.deb
=> Add securedrop-export-0.3.0 bullseye package

workstation/bullseye/securedrop-proxy_0.4.0+bullseye_all.deb
=> Add securedrop-proxy-0.4.0 (bullseye)

workstation/bullseye/securedrop-workstation-viewer_0.2.0+bullseye_all.deb
=> add securedrop-workstation-viewer 0.2.0 package for bullseye

workstation/bullseye/securedrop-client_0.8.0+bullseye_all.deb
Signed-off-by: Allie Crevier <allie@freedom.press>
=> add securedrop-client 0.8.0 package for bullseye

core/focal/securedrop-app-code_2.4.1~rc1+focal_amd64.deb, core/focal/securedrop-config-0.1.4+2.4.1~rc1+focal-amd64.deb, core/focal/securedrop-keyring-0.1.6+2.4.1~rc1+focal-amd64.deb, core/focal/securedrop-ossec-agent-3.6.0+2.4.1~rc1+focal-amd64.deb, core/focal/securedrop-ossec-server-3.6.0+2.4.1~rc1+focal-amd64.deb
=> Added SecureDrop 2.4.1-rc1 packages

core/focal/linux-headers-5.15.57-grsec-securedrop_5.15.57-grsec-securedrop-1_amd64.deb, core/focal/linux-image-5.15.57-grsec-securedrop_5.15.57-grsec-securedrop-1_amd64.deb
=> Added core 5.15.57 grsec kernel packages

core/focal/securedrop-app-code_2.4.2~rc1+focal_amd64.deb, core/focal/securedrop-config-0.1.4+2.4.2~rc1+focal-amd64.deb, core/focal/securedrop-grsec-5.15.57+focal-amd64.deb, core/focal/securedrop-keyring-0.1.6+2.4.2~rc1+focal-amd64.deb, core/focal/securedrop-ossec-agent-3.6.0+2.4.2~rc1+focal-amd64.deb, core/focal/securedrop-ossec-server-3.6.0+2.4.2~rc1+focal-amd64.deb
=> Add SecureDrop 2.4.2-rc1 debs

repo/conf/distributions
Refs https://github.com/freedomofpress/securedrop-debian-packaging/issues/369.
This will do nothing on its own until we start building bookworm packages.
=> Add bookworm repository configuration

core/focal/securedrop-app-code_2.5.0~rc1+focal_amd64.deb, core/focal/securedrop-config-0.1.4+2.5.0~rc1+focal-amd64.deb, core/focal/securedrop-keyring-0.1.6+2.5.0~rc1+focal-amd64.deb, core/focal/securedrop-ossec-agent-3.6.0+2.5.0~rc1+focal-amd64.deb, core/focal/securedrop-ossec-server-3.6.0+2.5.0~rc1+focal-amd64.deb
=> Add SecureDrop 2.5.0-rc1 packages

core/focal/securedrop-app-code_2.5.0~rc3+focal_amd64.deb, core/focal/securedrop-config-0.1.4+2.5.0~rc3+focal-amd64.deb, core/focal/securedrop-keyring-0.1.6+2.5.0~rc3+focal-amd64.deb, core/focal/securedrop-ossec-agent-3.6.0+2.5.0~rc3+focal-amd64.deb, core/focal/securedrop-ossec-server-3.6.0+2.5.0~rc3+focal-amd64.deb
**NB.**  No packages were published for the aborted SecureDrop 2.5.0-rc2.
=> add SecureDrop 2.5.0-rc3 packages

core/focal/linux-headers-5.15.81-grsec-securedrop_5.15.81-grsec-securedrop-1_amd64.deb, core/focal/linux-image-5.15.81-grsec-securedrop_5.15.81-grsec-securedrop-1_amd64.deb, core/focal/securedrop-grsec_5.15.81-grsec-securedrop-1_amd64.deb, workstation/bullseye/linux-headers-5.15.81-grsec-workstation_5.15.81-grsec-workstation-1_amd64.deb, workstation/bullseye/linux-image-5.15.81-grsec-workstation_5.15.81-grsec-workstation-1_amd64.deb, workstation/bullseye/securedrop-workstation-grsec_5.15.81-grsec-workstation-1_amd64.deb
Refs https://github.com/freedomofpress/securedrop/issues/6697
Refs https://github.com/freedomofpress/securedrop-workstation/issues/847
=> Add Linux 5.15.81 packages

.github/PULL_REQUEST_TEMPLATE.md
Refs https://github.com/freedomofpress/securedrop-builder/issues/304.
=> Update pull request template for securedrop-builder rename

core/focal/linux-headers-5.15.89-grsec-securedrop_5.15.89-grsec-securedrop-1_amd64.deb, core/focal/linux-image-5.15.89-grsec-securedrop_5.15.89-grsec-securedrop-1_amd64.deb, core/focal/securedrop-grsec_5.15.89-grsec-securedrop-1_amd64.deb, workstation/bullseye/linux-headers-5.15.89-grsec-workstation_5.15.89-grsec-workstation-1_amd64.deb, workstation/bullseye/linux-image-5.15.89-grsec-workstation_5.15.89-grsec-workstation-1_amd64.deb, workstation/bullseye/securedrop-workstation-grsec_5.15.89-grsec-workstation-1_amd64.deb
=> add Linux 5.15.89 grsec kernels

core/focal/securedrop-app-code_2.5.2~rc1+focal_amd64.deb, core/focal/securedrop-config-0.1.4+2.5.2~rc1+focal-amd64.deb, core/focal/securedrop-keyring-0.1.6+2.5.2~rc1+focal-amd64.deb, core/focal/securedrop-ossec-agent-3.6.0+2.5.2~rc1+focal-amd64.deb, core/focal/securedrop-ossec-server-3.6.0+2.5.2~rc1+focal-amd64.deb
Contains SecureDrop 2.5.2-rc1 debian packages (excluding securedrop-grsec, which is now built elsewhere)
=> Add 2.5.2-rc1 securedrop packages

workstation/bullseye/securedrop-client_0.9.0-rc1+bullseye_all.deb
=> add securedrop-client 0.9.0-rc1 package

workstation/bullseye/securedrop-client_0.9.0-rc2+bullseye_all.deb
=> Add securedrop-client 0.9.0-rc2 package

core/focal/linux-headers-5.15.98-1-grsec-securedrop_5.15.98-1-grsec-securedrop-1_amd64.deb, core/focal/linux-image-5.15.98-1-grsec-securedrop_5.15.98-1-grsec-securedrop-1_amd64.deb, core/focal/securedrop-grsec_5.15.98-1-grsec-securedrop-1_amd64.deb, workstation/bullseye/linux-headers-5.15.98-1-grsec-workstation_5.15.98-1-grsec-workstation-1_amd64.deb, workstation/bullseye/linux-image-5.15.98-1-grsec-workstation_5.15.98-1-grsec-workstation-1_amd64.deb, workstation/bullseye/securedrop-workstation-grsec_5.15.98-1-grsec-workstation-1_amd64.deb
These packages were built using the currently un-merged changes in https://github.com/freedomofpress/kernel-builder/pull/33.
Refs <https://github.com/freedomofpress/securedrop/issues/6765>.
Refs <https://github.com/freedomofpress/securedrop-workstation/issues/860>.
=> Add Linux 5.15.98 packages

workstation/bullseye/securedrop-client_0.9.0-rc3+bullseye_all.deb
=> Added securedrop-client 0.9.0-rc3 package

.github/workflows/ci.yml
CI verifies that newly added packages had a buildinfo file
pushed to the build-logs repository and the package checksum
matches that.
The check-buildinfo script was added in <https://github.com/freedomofpress/securedrop-builder/pull/423>.
Refs <https://github.com/freedomofpress/securedrop/issues/6356>.
----
Once this is merged I'll submit the same change to securedrop-apt-prod.
=> Have CI verify new packages match buildinfo files

workstation/bullseye/securedrop-proxy_0.4.1~rc1+bullseye_all.deb
Refs <https://github.com/freedomofpress/securedrop-proxy/issues/116>.
=> Add securedrop-proxy 0.4.1~rc1

workstation/bullseye/securedrop-keyring_0.1.7+bullseye_all.deb
Refs <https://github.com/freedomofpress/securedrop-builder/issues/437>.
=> Add securedrop-keyring 0.1.7

core/focal/securedrop-grsec_5.15.89-grsec-securedrop-2_amd64.deb, core/focal/securedrop-grsec_5.15.98-1-grsec-securedrop-1_amd64.deb
Fixes https://github.com/freedomofpress/securedrop/issues/6789
Add securedrop-grsec 5.15.89-2, see https://github.com/freedomofpress/securedrop/issues/6789 for more details on how the package was constructed and test plan for it. 5.15.98-1 is removed since it's a higher version and it was buggy and we're not going to be shipping that kernel version anymore.
After this is merged, manual intervention will be needed on the apt-test server since we need to override the higher versioned package, I'll take care of that when it's time.
=> Add securedrop-grsec 5.15.89-2

workstation/bullseye/securedrop-keyring_0.2.0+bullseye_all.deb
Add securedrop-keyring-0.2.0 (note: built from a prod-signed tag and not built with rc number. Anticipating promoting to prod.) 
Towards https://github.com/freedomofpress/securedrop-builder/issues/443
=> Add securedrop-keyring-0.2.0

core/focal/securedrop-app-code_2.6.0~rc1+focal_amd64.deb, core/focal/securedrop-config_2.6.0~rc1+focal_all.deb, core/focal/securedrop-keyring_0.2.1+2.6.0~rc1+focal_all.deb, core/focal/securedrop-ossec-agent_3.6.0+2.6.0~rc1+focal_all.deb, core/focal/securedrop-ossec-server_3.6.0+2.6.0~rc1+focal_all.deb
Refs <https://github.com/freedomofpress/securedrop/issues/6798>.
=> Add SecureDrop 2.6.0-rc1

core/focal/securedrop-app-code_2.6.0~rc2+focal_amd64.deb, core/focal/securedrop-config_2.6.0~rc2+focal_all.deb, core/focal/securedrop-keyring_0.2.1+2.6.0~rc2+focal_all.deb, core/focal/securedrop-ossec-agent_3.6.0+2.6.0~rc2+focal_all.deb, core/focal/securedrop-ossec-server_3.6.0+2.6.0~rc2+focal_all.deb
=> added securedrop 2.6.0-rc2 debs

core/focal/linux-headers-5.15.120-1-grsec-securedrop_5.15.120-1-grsec-securedrop-1_amd64.deb, core/focal/linux-image-5.15.120-1-grsec-securedrop_5.15.120-1-grsec-securedrop-1_amd64.deb, core/focal/securedrop-grsec_5.15.120-1-grsec-securedrop-1_amd64.deb, workstation/bullseye/linux-headers-5.15.120-1-grsec-workstation_5.15.120-1-grsec-workstation-1_amd64.deb, workstation/bullseye/linux-image-5.15.120-1-grsec-workstation_5.15.120-1-grsec-workstation-1_amd64.deb, workstation/bullseye/securedrop-workstation-grsec_5.15.120-1-grsec-workstation-1_amd64.deb
Work in progress
Refs https://github.com/freedomofpress/securedrop/issues/6887
Refs https://github.com/freedomofpress/securedrop-workstation/issues/907
=> Add securedrop-grsec-5.15.120-1 and securedrop-workstation-grsec-5.15.120-1

core/focal/securedrop-grsec_5.15.120-1-grsec-securedrop-2_amd64.deb
Same as -1, except it adds in a dependency on amd64-microcode (see <https://github.com/freedomofpress/kernel-builder/pull/37>).
Run diffoscope against `securedrop-grsec_5.15.120-1-grsec-securedrop-1_amd64.deb` in the same folder, the packages should be identical except for version and the amd64-microcode dependency:
```
user@dev ~/g/f/s/c/focal> diffoscope securedrop-grsec_5.15.120-1-grsec-securedrop-1_amd64.deb securedrop-grsec_5.15.120-1-grsec-securedrop-2_amd64.deb
--- securedrop-grsec_5.15.120-1-grsec-securedrop-1_amd64.deb
+++ securedrop-grsec_5.15.120-1-grsec-securedrop-2_amd64.deb
├── file list
│ @@ -1,3 +1,3 @@
│  -rw-r--r--   0        0        0        4 2011-06-29 20:23:37.000000 debian-binary
│ --rw-r--r--   0        0        0     1512 2011-06-29 …
```
=> Add securedrop-grsec_5.15.120-1-grsec-securedrop-2_amd64.deb

core/focal/linux-headers-5.15.123-1-grsec-securedrop_5.15.123-1-grsec-securedrop-1_amd64.deb, core/focal/linux-image-5.15.123-1-grsec-securedrop_5.15.123-1-grsec-securedrop-1_amd64.deb, core/focal/securedrop-grsec_5.15.123-1-grsec-securedrop-1_amd64.deb, workstation/bullseye/linux-headers-5.15.123-1-grsec-workstation_5.15.123-1-grsec-workstation-1_amd64.deb, workstation/bullseye/linux-image-5.15.123-1-grsec-workstation_5.15.123-1-grsec-workstation-1_amd64.deb, workstation/bullseye/securedrop-workstation-grsec_5.15.123-1-grsec-workstation-1_amd64.deb
Refs <https://github.com/freedomofpress/securedrop/issues/6906>.
Refs <https://github.com/freedomofpress/securedrop-workstation/issues/911>.
=> Add Linux 5.15.123 packages

core/focal/linux-headers-5.15.130-1-grsec-securedrop_5.15.130-1-grsec-securedrop-1_amd64.deb, core/focal/linux-image-5.15.130-1-grsec-securedrop_5.15.130-1-grsec-securedrop-1_amd64.deb, core/focal/securedrop-grsec_5.15.130-1-grsec-securedrop-1_amd64.deb, workstation/bullseye/linux-headers-5.15.130-1-grsec-workstation_5.15.130-1-grsec-workstation-1_amd64.deb, workstation/bullseye/linux-image-5.15.130-1-grsec-workstation_5.15.130-1-grsec-workstation-1_amd64.deb, workstation/bullseye/securedrop-workstation-grsec_5.15.130-1-grsec-workstation-1_amd64.deb
Towards:
- freedomofpress/securedrop#6938
- freedomofpress/securedrop-workstation#916
=> add Linux 5.15.130 packages

core/focal/linux-headers-5.15.131-1-grsec-securedrop_5.15.131-1-grsec-securedrop-1_amd64.deb, core/focal/linux-image-5.15.131-1-grsec-securedrop_5.15.131-1-grsec-securedrop-1_amd64.deb, core/focal/securedrop-grsec_5.15.131-1-grsec-securedrop-1_amd64.deb, workstation/bullseye/linux-headers-5.15.131-1-grsec-workstation_5.15.131-1-grsec-workstation-1_amd64.deb, workstation/bullseye/linux-image-5.15.131-1-grsec-workstation_5.15.131-1-grsec-workstation-1_amd64.deb, workstation/bullseye/securedrop-workstation-grsec_5.15.131-1-grsec-workstation-1_amd64.deb
Originally [intended][1] just to rebuild #202 with
freedomofpress/kernel-builder#38, this also moved us from v5.15.30 to v5.15.131.
Towards:
- freedomofpress/securedrop#6938
- freedomofpress/securedrop-workstation#916
[1]: https://github.com/freedomofpress/securedrop/issues/6938#issuecomment-1709126141
```sh-session
user@sd-dev:~/securedrop-apt-test$ debdiff core/focal/securedrop-grsec_5.15.130-1-grsec-securedrop-1_amd64.deb core/focal/securedrop-grsec_5.15.131-1-grsec-securedrop-1_amd64.deb 
File lists identical (after any substitutions)
Control files: lines which differ (wdiff format)
------------------------------------------------
Depends: [-linux-image-5.15.130-1-grsec-securedrop,-] {+linux-image-5.15.131-1-grsec-securedrop,+} intel-microcode, amd64-microcode, …
```
=> add Linux 5.15.131 packages

core/focal/linux-headers-5.15.135-1-grsec-securedrop_5.15.135-1-grsec-securedrop-1_amd64.deb, core/focal/linux-image-5.15.135-1-grsec-securedrop_5.15.135-1-grsec-securedrop-1_amd64.deb, core/focal/securedrop-grsec_5.15.135-1-grsec-securedrop-1_amd64.deb, workstation/bullseye/linux-headers-5.15.135-1-grsec-workstation_5.15.135-1-grsec-workstation-1_amd64.deb, workstation/bullseye/linux-image-5.15.135-1-grsec-workstation_5.15.135-1-grsec-workstation-1_amd64.deb, workstation/bullseye/securedrop-workstation-grsec_5.15.135-1-grsec-workstation-1_amd64.deb
Towards [#6966](https://github.com/freedomofpress/securedrop/issues/6966)
- adds grsecurity-patched linux 5.15.135 kernels for securedrop core and workstation.
=> Add 5.15.135 server and workstation grsec kernels

core/focal/securedrop-app-code_2.7.0~rc2+focal_amd64.deb, core/focal/securedrop-config_2.7.0~rc2+focal_all.deb, core/focal/securedrop-keyring_0.2.1+2.7.0~rc2+focal_all.deb, core/focal/securedrop-ossec-agent_3.6.0+2.7.0~rc2+focal_all.deb, core/focal/securedrop-ossec-server_3.6.0+2.7.0~rc2+focal_all.deb
=> Add Securedrop 2.7.0~rc2 Debian packages

core/focal/linux-headers-5.15.140-1-grsec-securedrop_5.15.140-1-grsec-securedrop-1_amd64.deb, core/focal/linux-image-5.15.140-1-grsec-securedrop_5.15.140-1-grsec-securedrop-1_amd64.deb, core/focal/securedrop-grsec_5.15.140-1-grsec-securedrop-1_amd64.deb, workstation/bullseye/linux-headers-5.15.140-1-grsec-workstation_5.15.140-1-grsec-workstation-1_amd64.deb, workstation/bullseye/linux-image-5.15.140-1-grsec-workstation_5.15.140-1-grsec-workstation-1_amd64.deb, workstation/bullseye/securedrop-workstation-grsec_5.15.140-1-grsec-workstation-1_amd64.deb
Towards https://github.com/freedomofpress/securedrop/issues/7082
- adds grsecurity-patched linux 5.15.140 kernels for securedrop core and workstation.
=> Add 5.15.140 grsec kernels

.github/workflows/cleanup.yml, scripts/clean-old-packages
Instead of having each job and script be responsible for cleaning up, let's have CI trigger cleanup on every push into the main branch. The clean-old-packages script is copied from securedrop-builder with the RPM parts removed.
Fixes #211.
=> Run clean-old-packages on push

core/focal/linux-headers-5.15.148-1-grsec-securedrop_5.15.148-1-grsec-securedrop-1_amd64.deb, core/focal/linux-image-5.15.148-1-grsec-securedrop_5.15.148-1-grsec-securedrop-1_amd64.deb, core/focal/securedrop-grsec_5.15.148-1-grsec-securedrop-1_amd64.deb, workstation/bullseye/linux-headers-5.15.148-1-grsec-workstation_5.15.148-1-grsec-workstation-1_amd64.deb, workstation/bullseye/linux-image-5.15.148-1-grsec-workstation_5.15.148-1-grsec-workstation-1_amd64.deb, workstation/bullseye/securedrop-workstation-grsec_5.15.148-1-grsec-workstation-1_amd64.deb
Refs https://github.com/freedomofpress/securedrop/issues/7113.
Refs https://github.com/freedomofpress/securedrop-workstation/issues/950.
=> Add Linux 5.15.148 packages

core/focal/securedrop-app-code_2.8.0~rc1+focal_amd64.deb, core/focal/securedrop-config_2.8.0~rc1+focal_all.deb, core/focal/securedrop-keyring_0.2.1+2.8.0~rc1+focal_all.deb, core/focal/securedrop-ossec-agent_3.6.0+2.8.0~rc1+focal_all.deb, core/focal/securedrop-ossec-server_3.6.0+2.8.0~rc1+focal_all.deb
Refs <https://github.com/freedomofpress/securedrop/issues/7121>.
=> Add SecureDrop 2.8.0-rc1

workstation/bullseye/securedrop-client_0.10.0~rc1+bullseye_all.deb, workstation/bullseye/securedrop-export_0.10.0~rc1+bullseye_all.deb, workstation/bullseye/securedrop-keyring_0.10.0~rc1+bullseye_all.deb, workstation/bullseye/securedrop-log_0.10.0~rc1+bullseye_all.deb, workstation/bullseye/securedrop-proxy_0.10.0~rc1+bullseye_all.deb, workstation/bullseye/securedrop-workstation-config_0.10.0~rc1+bullseye_all.deb, workstation/bullseye/securedrop-workstation-viewer_0.10.0~rc1+bullseye_all.deb
Refs <https://github.com/freedomofpress/securedrop-client/issues/1867>.
=> Add securedrop-client 0.10.0-rc1

workstation/bullseye/securedrop-client_0.10.0~rc2+bullseye_all.deb, workstation/bullseye/securedrop-export_0.10.0~rc2+bullseye_all.deb, workstation/bullseye/securedrop-keyring_0.10.0~rc2+bullseye_all.deb, workstation/bullseye/securedrop-log_0.10.0~rc2+bullseye_all.deb, workstation/bullseye/securedrop-proxy_0.10.0~rc2+bullseye_all.deb, workstation/bullseye/securedrop-workstation-config_0.10.0~rc2+bullseye_all.deb, workstation/bullseye/securedrop-workstation-viewer_0.10.0~rc2+bullseye_all.deb
build-logs pushed in <https://github.com/freedomofpress/build-logs/commit/29d0bc42530a035e9ddd22b0107670b870dfa822>.
Refs <https://github.com/freedomofpress/securedrop-client/issues/1867>.
=> Add SecureDrop Client 0.10.0-rc2 packages

workstation/bullseye/securedrop-client_0.10.0~rc3+bullseye_all.deb, workstation/bullseye/securedrop-export_0.10.0~rc3+bullseye_all.deb, workstation/bullseye/securedrop-keyring_0.10.0~rc3+bullseye_all.deb, workstation/bullseye/securedrop-log_0.10.0~rc3+bullseye_all.deb, workstation/bullseye/securedrop-proxy_0.10.0~rc3+bullseye_all.deb, workstation/bullseye/securedrop-workstation-config_0.10.0~rc3+bullseye_all.deb, workstation/bullseye/securedrop-workstation-viewer_0.10.0~rc3+bullseye_all.deb
build-logs pushed in
<https://github.com/freedomofpress/build-logs/commit/59a0e8436e6477a30dcab1f3bbc60192ef8d2456>.
Refs <https://github.com/freedomofpress/securedrop-client/issues/1867>.
=> Add SecureDrop Client 0.10.0-rc3 packages

workstation/bookworm/linux-headers-6.6.22-grsec-workstation-1_6.6.22-grsec-workstation-1_amd64.deb, workstation/bookworm/linux-image-6.6.22-grsec-workstation-1_6.6.22-grsec-workstation-1_amd64.deb, workstation/bookworm/securedrop-grsec_6.6.22-grsec-workstation-1_amd64.deb
build-logs pushed in
<https://github.com/freedomofpress/build-logs/commit/b30e6ce367ef5b03671044fd42ac04222dbf238e>.
There are a few issues with this kernel, notably the packaging and version numbers are off.
Also I haven't tried it yet.
=> Add workstation 6.6.22 kernel

workstation/bookworm/paxctld_1.2.5-1_amd64.deb
It hasn't been available in Debian since buster, see b9f9e1f88ca64e19.
=> Copy paxctld from bullseye to bookworm

.github/workflows/update-tor.yml, scripts/new-tor-issue
Refs https://github.com/freedomofpress/securedrop-builder/issues/482
The `new-tor-issue` script and parts of the job code were imported from the `securedrop-builder` repo and authored by Kunal Mehta, see https://github.com/freedomofpress/securedrop-builder/pull/408 and https://github.com/freedomofpress/securedrop-builder/pull/287
Migrate logic for checking for and applying Tor updates to GitHub Actions
=> Add GitHub Action for Tor update check

workstation/bookworm/linux-headers-6.6.22-2-grsec-workstation_6.6.22-2-grsec-workstation-2_amd64.deb, workstation/bookworm/linux-image-6.6.22-2-grsec-workstation_6.6.22-2-grsec-workstation-2_amd64.deb, workstation/bookworm/securedrop-workstation-grsec_6.6.22-2-grsec-workstation-2_amd64.deb
* Now with the correct metapackage
* Also more netfilter modules enabled
=> Add 6.6.22-2 workstation Linux kernel

workstation/bookworm/xpp_1.5-cvs20081009-4_amd64.deb
Adds `xpp` package under bookworm as well as bullseye, to allow for installation of the current securedrop-export package.
=> Add xpp package to Bookworm

core/focal/linux-headers-5.15.152-1-grsec-securedrop_5.15.152-1-grsec-securedrop-1_amd64.deb, core/focal/linux-image-5.15.152-1-grsec-securedrop_5.15.152-1-grsec-securedrop-1_amd64.deb, core/focal/securedrop-grsec_5.15.152-1-grsec-securedrop-1_amd64.deb, workstation/bullseye/linux-headers-5.15.152-1-grsec-workstation_5.15.152-1-grsec-workstation-1_amd64.deb, workstation/bullseye/linux-image-5.15.152-1-grsec-workstation_5.15.152-1-grsec-workstation-1_amd64.deb, workstation/bullseye/securedrop-workstation-grsec_5.15.152-1-grsec-workstation-1_amd64.deb
Add Linux 5.15.152 grsec kernels (core and workstation)
(Note: kernels untested. Source tarballs retained.)
=> Add Linux 5.15.152 grsec kernels

.github/workflows/update-tor.yml
Our cwd is the root of this Git repository, so we don't need to go up one level.
See failure in https://github.com/freedomofpress/securedrop-apt-test/actions/runs/8671817813/job/23781419721
=> Fix path to new-tor-issue script

workstation/bookworm/linux-headers-6.6.25-1-grsec-workstation_6.6.25-1-grsec-workstation-1_amd64.deb, workstation/bookworm/linux-image-6.6.25-1-grsec-workstation_6.6.25-1-grsec-workstation-1_amd64.deb, workstation/bookworm/securedrop-workstation-grsec_6.6.25-1-grsec-workstation-1_amd64.deb
Notably includes the `uname -r` version fix.
=> Add Linux 6.6.25 for workstation

workstation/bookworm/linux-headers-6.6.28-1-grsec-workstation_6.6.28-1-grsec-workstation-1_amd64.deb, workstation/bookworm/linux-image-6.6.28-1-grsec-workstation_6.6.28-1-grsec-workstation-1_amd64.deb, workstation/bookworm/securedrop-workstation-grsec_6.6.28-1-grsec-workstation-1_amd64.deb
Add 6.6.28 grsec kernels (workstation bookworm)
See https://github.com/freedomofpress/kernel-builder/pull/45
=> Add 6.6.28 workstastation grsec kernels

workstation/bookworm/linux-headers-6.6.31-1-grsec-workstation_6.6.31-1-grsec-workstation-1_amd64.deb, workstation/bookworm/linux-image-6.6.31-1-grsec-workstation_6.6.31-1-grsec-workstation-1_amd64.deb, workstation/bookworm/securedrop-workstation-grsec_6.6.31-1-grsec-workstation-1_amd64.deb
=> Add Linux 6.6.31 workstation kernels

core/focal/securedrop-app-code_2.9.0~rc1+focal_amd64.deb, core/focal/securedrop-config_2.9.0~rc1+focal_all.deb, core/focal/securedrop-keyring_0.2.2+2.9.0~rc1+focal_all.deb, core/focal/securedrop-ossec-agent_3.6.0+2.9.0~rc1+focal_all.deb, core/focal/securedrop-ossec-server_3.6.0+2.9.0~rc1+focal_all.deb
=> add SecureDrop 2.9.0-rc1 packages

core/focal/linux-headers-5.15.160-1-grsec-securedrop_5.15.160-1-grsec-securedrop-1_amd64.deb, core/focal/linux-image-5.15.160-1-grsec-securedrop_5.15.160-1-grsec-securedrop-1_amd64.deb, core/focal/securedrop-grsec_5.15.160-1-grsec-securedrop-1_amd64.deb
Note: this was using the patch in https://github.com/freedomofpress/kernel-builder/pull/51.
=> Add server 5.15.160 Linux kernel

workstation/bookworm-nightlies/securedrop-qubesdb_0.10.1.dev20240602060458+bookworm_all.deb, workstation/bookworm-nightlies/securedrop-qubesdb_0.10.1.dev20240603060452+bookworm_all.deb, workstation/bookworm-nightlies/securedrop-qubesdb_0.10.1.dev20240603205102+bookworm_all.deb, workstation/bookworm-nightlies/securedrop-qubesdb_0.10.1.dev20240603211144+bookworm_all.deb
freedomofpress/securedrop-client#2051 renamed `securedrop-qubesdb` to `securedrop-qubesdb-tools`.  This removes the orphaned `securedrop-qubesdb` packages.
=> chore: remove `securedrop-qubesdb` in favor of `securedrop-qubesdb-tools`

core/focal/securedrop-app-code_2.9.0~rc2+focal_amd64.deb, core/focal/securedrop-config_2.9.0~rc2+focal_all.deb, core/focal/securedrop-keyring_0.2.2+2.9.0~rc2+focal_all.deb, core/focal/securedrop-ossec-agent_3.6.0+2.9.0~rc2+focal_all.deb, core/focal/securedrop-ossec-server_3.6.0+2.9.0~rc2+focal_all.deb
=> Add debs for SecureDrop 2.9.0-rc2

workstation/bookworm/securedrop-client_0.11.0~rc1+bookworm_all.deb, workstation/bookworm/securedrop-export_0.11.0~rc1+bookworm_all.deb, workstation/bookworm/securedrop-keyring_0.11.0~rc1+bookworm_all.deb, workstation/bookworm/securedrop-log_0.11.0~rc1+bookworm_all.deb, workstation/bookworm/securedrop-proxy_0.11.0~rc1+bookworm_amd64.deb, workstation/bookworm/securedrop-qubesdb-tools_0.11.0~rc1+bookworm_all.deb, workstation/bookworm/securedrop-whonix-config_0.11.0~rc1+bookworm_all.deb, workstation/bookworm/securedrop-workstation-config_0.11.0~rc1+bookworm_all.deb, workstation/bookworm/securedrop-workstation-viewer_0.11.0~rc1+bookworm_all.deb
Adds bookworm securedrop-client packages.
=> Add 0.11.0-rc1Bookworm  client packages

core/focal/securedrop-app-code_2.9.0~rc3+focal_amd64.deb, core/focal/securedrop-config_2.9.0~rc3+focal_all.deb, core/focal/securedrop-keyring_0.2.2+2.9.0~rc3+focal_all.deb, core/focal/securedrop-ossec-agent_3.6.0+2.9.0~rc3+focal_all.deb, core/focal/securedrop-ossec-server_3.6.0+2.9.0~rc3+focal_all.deb
=> Add securedrop 2.9.0-rc3 debs

workstation/bullseye/securedrop-keyring_0.10.2~rc1+bullseye_all.deb
Refs https://github.com/freedomofpress/securedrop-client/issues/2049
Adds only the securedrop-keyring package from 0.10.2-rc1 build.
=> Add securedrop-keyring-0.10.2-rc1

workstation/bookworm/securedrop-client_0.11.0~rc2+bookworm_all.deb, workstation/bookworm/securedrop-export_0.11.0~rc2+bookworm_all.deb, workstation/bookworm/securedrop-keyring_0.11.0~rc2+bookworm_all.deb, workstation/bookworm/securedrop-log_0.11.0~rc2+bookworm_all.deb, workstation/bookworm/securedrop-proxy-dbgsym_0.11.0~rc2+bookworm_amd64.deb, workstation/bookworm/securedrop-proxy_0.11.0~rc2+bookworm_amd64.deb, workstation/bookworm/securedrop-qubesdb-tools_0.11.0~rc2+bookworm_all.deb, workstation/bookworm/securedrop-whonix-config_0.11.0~rc2+bookworm_all.deb, workstation/bookworm/securedrop-workstation-config_0.11.0~rc2+bookworm_all.deb, workstation/bookworm/securedrop-workstation-viewer_0.11.0~rc2+bookworm_all.deb
Refs <https://github.com/freedomofpress/securedrop-workstation/issues/1103>.
=> Add SecureDrop Client 0.11.0-rc2

repo/conf/distributions
This just sets up the noble component, so people can later create a `core/noble` folder with debs.
The auto-fetching tor part isn't configured since Tor isn't providing noble packages yet (<https://github.com/freedomofpress/securedrop/issues/7250>).
Refs <https://github.com/freedomofpress/securedrop/issues/7210>.
=> Configure noble component

core/focal/linux-headers-5.15.167-1-grsec-securedrop_5.15.167-1-grsec-securedrop-1_amd64.deb, core/focal/linux-image-5.15.167-1-grsec-securedrop-dbg_5.15.167-1-grsec-securedrop-1_amd64.deb, core/focal/linux-image-5.15.167-1-grsec-securedrop_5.15.167-1-grsec-securedrop-1_amd64.deb, core/focal/securedrop-grsec_5.15.167-1-grsec-securedrop-1_amd64.deb, workstation/bookworm/linux-headers-6.6.56-1-grsec-workstation_6.6.56-1-grsec-workstation-1_amd64.deb, workstation/bookworm/linux-image-6.6.56-1-grsec-workstation-dbg_6.6.56-1-grsec-workstation-1_amd64.deb, workstation/bookworm/linux-image-6.6.56-1-grsec-workstation_6.6.56-1-grsec-workstation-1_amd64.deb, workstation/bookworm/securedrop-workstation-grsec_6.6.56-1-grsec-workstation-1_amd64.deb
- core: [buildinfo](https://github.com/freedomofpress/build-logs/commit/9d7a895c885b2649ec4ec4ab04383668110746f2), [build log](https://github.com/freedomofpress/build-logs/commit/81273e08f87e48f5a640406bb219dafc05ac49dc)
- workstation:   https://github.com/freedomofpress/build-logs/commit/68207d29b21c9a72cbab0fb11b8507a1e35eea06
=> Add SecureDrop 5.15.167 and SecureDrop Workstation 6.6.56 grsec kernels

core/focal/linux-image-5.15.167-1-grsec-securedrop-dbg_5.15.167-1-grsec-securedrop-1_amd64.deb, workstation/bookworm/linux-image-6.6.56-1-grsec-workstation-dbg_6.6.56-1-grsec-workstation-1_amd64.deb
While it's nice to have them, they're giant and seem to be causing our package repository server to OOM.
Refs <https://github.com/freedomofpress/infrastructure/issues/5131>.
=> Don't upload the dbg kernel packages

core/noble/paxctld_1.2.6-1_amd64.deb
Downloaded from <https://grsecurity.net/paxctld/paxctld_1.2.6-1_amd64.deb> and verified:
```
gpg: Signature made Wed Sep 25 09:30:02 2024 EDT
gpg:                using RSA key DE9452CE46F42094907F108B44D1C0F82525FE49
gpg: Good signature from "Bradley Spengler (spender) <spender@grsecurity.net>" [unknown]
gpg:                 aka "Bradley Spengler <brad.spengler@grsecurity.net>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: DE94 52CE 46F4 2094 907F  108B 44D1 C0F8 2525 FE49
```
=> Add paxctld 1.2.6 for noble

core/noble/linux-headers-6.6.57-1-grsec-securedrop_6.6.57-1-grsec-securedrop-1_amd64.deb, core/noble/linux-image-6.6.57-1-grsec-securedrop_6.6.57-1-grsec-securedrop-1_amd64.deb, core/noble/securedrop-grsec_6.6.57-1-grsec-securedrop-1_amd64.deb
Note that this was built using https://github.com/freedomofpress/kernel-builder/pull/54, so that can probably be merged too now.
I tested the kernel on a NUC 10 with noble and it booted.
=> Add Linux 6.6.57 for server on noble

core/noble/linux-headers-6.6.58-1-grsec-securedrop_6.6.58-1-grsec-securedrop-1_amd64.deb, core/noble/linux-image-6.6.58-1-grsec-securedrop_6.6.58-1-grsec-securedrop-1_amd64.deb, core/noble/securedrop-grsec_6.6.58-1-grsec-securedrop-1_amd64.deb
Contains extra netfilter modules for nftables; see https://github.com/freedomofpress/kernel-builder/pull/54.
=> Add Linux 6.6.58 server kernels

.github/workflows/update-tor.yml, repo/conf/distributions, repo/conf/updates
The next nightly run will pull them in.
Fixes <https://github.com/freedomofpress/securedrop/issues/7250>.
I've already verified this, but for completeness:
```
root@bd5061c646a3:/src# ls repo/pool/main/t/tor/
tor-geoipdb_0.4.8.13-2~focal+1_all.deb	tor-geoipdb_0.4.8.13-2~noble+1_all.deb	tor_0.4.8.13-2~focal+1_amd64.deb  tor_0.4.8.13-2~noble+1_amd64.deb
```
=> Import Tor packages for noble too

core/focal/linux-headers-5.15.172-1-grsec-securedrop_5.15.172-1-grsec-securedrop-1_amd64.deb, core/focal/linux-image-5.15.172-1-grsec-securedrop_5.15.172-1-grsec-securedrop-1_amd64.deb, core/focal/securedrop-grsec_5.15.172-1-grsec-securedrop-1_amd64.deb, core/noble/linux-headers-6.6.61-1-grsec-securedrop_6.6.61-1-grsec-securedrop-1_amd64.deb, core/noble/linux-image-6.6.61-1-grsec-securedrop_6.6.61-1-grsec-securedrop-1_amd64.deb, core/noble/securedrop-grsec_6.6.61-1-grsec-securedrop-1_amd64.deb, workstation/bookworm/linux-headers-6.6.61-1-grsec-workstation_6.6.61-1-grsec-workstation-1_amd64.deb, workstation/bookworm/linux-image-6.6.61-1-grsec-workstation_6.6.61-1-grsec-workstation-1_amd64.deb, workstation/bookworm/securedrop-workstation-grsec_6.6.61-1-grsec-workstation-1_amd64.deb
This includes the latest changes from kernel-builder, especially https://github.com/freedomofpress/kernel-builder/pull/55 (setting ipv4 sysctl flags on the server).
=> Add server 5.15.172 and 6.6.61 kernels; Add workstation 6.6.61 kernel

core/focal/linux-headers-5.15.173-1-grsec-securedrop_5.15.173-1-grsec-securedrop-1_amd64.deb, core/focal/linux-image-5.15.173-1-grsec-securedrop_5.15.173-1-grsec-securedrop-1_amd64.deb, core/focal/securedrop-grsec_5.15.173-1-grsec-securedrop-1_amd64.deb, core/noble/linux-headers-6.6.62-1-grsec-securedrop_6.6.62-1-grsec-securedrop-1_amd64.deb, core/noble/linux-image-6.6.62-1-grsec-securedrop_6.6.62-1-grsec-securedrop-1_amd64.deb, core/noble/securedrop-grsec_6.6.62-1-grsec-securedrop-1_amd64.deb
These metapackages contain the fix from https://github.com/freedomofpress/kernel-builder/pull/57
=> Add 5.15.173 and 6.6.62 server kernels

core/focal/securedrop-app-code-dbgsym_2.11.0~rc1+focal_amd64.deb, core/focal/securedrop-app-code_2.11.0~rc1+focal_amd64.deb, core/focal/securedrop-config-dbgsym_2.11.0~rc1+focal_amd64.deb, core/focal/securedrop-config_2.11.0~rc1+focal_amd64.deb, core/focal/securedrop-keyring_0.2.2+2.11.0~rc1+focal_all.deb, core/focal/securedrop-ossec-agent_3.6.0+2.11.0~rc1+focal_all.deb, core/focal/securedrop-ossec-server_3.6.0+2.11.0~rc1+focal_all.deb
=> Add SecureDrop 2.11.0-rc1 packages

core/focal/securedrop-app-code-dbgsym_2.11.0~rc2+focal_amd64.deb, core/focal/securedrop-app-code_2.11.0~rc2+focal_amd64.deb, core/focal/securedrop-config-dbgsym_2.11.0~rc2+focal_amd64.deb, core/focal/securedrop-config_2.11.0~rc2+focal_amd64.deb, core/focal/securedrop-keyring_0.2.2+2.11.0~rc2+focal_all.deb, core/focal/securedrop-ossec-agent_3.6.0+2.11.0~rc2+focal_all.deb, core/focal/securedrop-ossec-server_3.6.0+2.11.0~rc2+focal_all.deb
=> Add SecureDrop 2.11.0-rc2 packages

core/noble/ossec-agent_3.6.0+noble_amd64.deb, core/noble/ossec-server_3.6.0+noble_amd64.deb
Built off the 2.11.1 tag.
build metadata pushed into <https://github.com/freedomofpress/build-logs/commit/a671ae7e180096d3f86ddbda330fa28f1730fe04>.
Refs <https://github.com/freedomofpress/securedrop/issues/7411>.
=> Add OSSEC noble packages

core/focal/securedrop-app-code-dbgsym_2.12.0~rc1+focal_amd64.deb, core/focal/securedrop-app-code_2.12.0~rc1+focal_amd64.deb, core/focal/securedrop-config-dbgsym_2.12.0~rc1+focal_amd64.deb, core/focal/securedrop-config_2.12.0~rc1+focal_amd64.deb, core/focal/securedrop-keyring_0.2.2+2.12.0~rc1+focal_all.deb, core/focal/securedrop-ossec-agent_3.6.0+2.12.0~rc1+focal_all.deb, core/focal/securedrop-ossec-server_3.6.0+2.12.0~rc1+focal_all.deb, core/noble/securedrop-app-code-dbgsym_2.12.0~rc1+noble_amd64.deb, core/noble/securedrop-app-code_2.12.0~rc1+noble_amd64.deb, core/noble/securedrop-config-dbgsym_2.12.0~rc1+noble_amd64.deb, core/noble/securedrop-config_2.12.0~rc1+noble_amd64.deb, core/noble/securedrop-keyring_0.2.2+2.12.0~rc1+noble_all.deb, core/noble/securedrop-ossec-agent_3.6.0+2.12.0~rc1+noble_all.deb, core/noble/securedrop-ossec-server_3.6.0+2.12.0~rc1+noble_all.deb
=> Add focal and noble SecureDrop 2.12.0-rc1 packages

core/focal/securedrop-app-code-dbgsym_2.12.0~rc3+focal_amd64.deb, core/focal/securedrop-app-code_2.12.0~rc3+focal_amd64.deb, core/focal/securedrop-config-dbgsym_2.12.0~rc3+focal_amd64.deb, core/focal/securedrop-config_2.12.0~rc3+focal_amd64.deb, core/focal/securedrop-keyring_0.2.2+2.12.0~rc3+focal_all.deb, core/focal/securedrop-ossec-agent_3.6.0+2.12.0~rc3+focal_all.deb, core/focal/securedrop-ossec-server_3.6.0+2.12.0~rc3+focal_all.deb, core/noble/securedrop-app-code-dbgsym_2.12.0~rc3+noble_amd64.deb, core/noble/securedrop-app-code_2.12.0~rc3+noble_amd64.deb, core/noble/securedrop-config-dbgsym_2.12.0~rc3+noble_amd64.deb, core/noble/securedrop-config_2.12.0~rc3+noble_amd64.deb, core/noble/securedrop-keyring_0.2.2+2.12.0~rc3+noble_all.deb, core/noble/securedrop-ossec-agent_3.6.0+2.12.0~rc3+noble_all.deb, core/noble/securedrop-ossec-server_3.6.0+2.12.0~rc3+noble_all.deb
=> SecureDrop 2.12.0-rc3

core/focal/linux-headers-5.15.179-1-grsec-securedrop_5.15.179-1-grsec-securedrop-1_amd64.deb, core/focal/linux-image-5.15.179-1-grsec-securedrop_5.15.179-1-grsec-securedrop-1_amd64.deb, core/focal/securedrop-grsec_5.15.179-1-grsec-securedrop-1_amd64.deb, core/noble/linux-headers-6.6.83-1-grsec-securedrop_6.6.83-1-grsec-securedrop-1_amd64.deb, core/noble/linux-image-6.6.83-1-grsec-securedrop_6.6.83-1-grsec-securedrop-1_amd64.deb, core/noble/securedrop-grsec_6.6.83-1-grsec-securedrop-1_amd64.deb, workstation/bookworm/linux-headers-6.6.83-1-grsec-workstation_6.6.83-1-grsec-workstation-1_amd64.deb, workstation/bookworm/linux-image-6.6.83-1-grsec-workstation_6.6.83-1-grsec-workstation-1_amd64.deb, workstation/bookworm/securedrop-workstation-grsec_6.6.83-1-grsec-workstation-1_amd64.deb
Notably the workstation kernel was built with <https://github.com/freedomofpress/kernel-builder/pull/60> to add exfat support.
Refs <https://github.com/freedomofpress/securedrop-workstation/issues/1267>.
- https://github.com/freedomofpress/build-logs/commit/bc810df48bfb8718b83ea76a5778b7fc8d476c0a
-  https://github.com/freedomofpress/build-logs/commit/11c42ab204be2eaa6625acecd2373f76f3ac9547
=> Add Linux 5.15.179 and 6.6.83 packages

.github/workflows/sign.yml
GHA is currently pushing two commits after new debs are committed because the output is not fully idempotent. Running build.py always modifies the repo/db/checksums.db file, which we already knew was a problem from securedrop-apt-prod's CI.
So the fix is to run build.py, if the only thing it touched is checksums.db, reset it and move on. The update metadata export step will get skipped because nothing has changed, and no new commit will be created.
Refs #267.
=> Fix double signing on pushes

core/focal/securedrop-app-code-dbgsym_2.12.2~rc1+focal_amd64.deb, core/focal/securedrop-app-code_2.12.2~rc1+focal_amd64.deb, core/focal/securedrop-config-dbgsym_2.12.2~rc1+focal_amd64.deb, core/focal/securedrop-config_2.12.2~rc1+focal_amd64.deb, core/focal/securedrop-keyring_0.2.2+2.12.2~rc1+focal_all.deb, core/focal/securedrop-ossec-agent_3.6.0+2.12.2~rc1+focal_all.deb, core/focal/securedrop-ossec-server_3.6.0+2.12.2~rc1+focal_all.deb, core/noble/securedrop-app-code-dbgsym_2.12.2~rc1+noble_amd64.deb, core/noble/securedrop-app-code_2.12.2~rc1+noble_amd64.deb, core/noble/securedrop-config-dbgsym_2.12.2~rc1+noble_amd64.deb, core/noble/securedrop-config_2.12.2~rc1+noble_amd64.deb, core/noble/securedrop-keyring_0.2.2+2.12.2~rc1+noble_all.deb, core/noble/securedrop-ossec-agent_3.6.0+2.12.2~rc1+noble_all.deb, core/noble/securedrop-ossec-server_3.6.0+2.12.2~rc1+noble_all.deb
=> Add SecureDrop  2.12.2-rc1 focal and noble packages.

core/focal/securedrop-app-code-dbgsym_2.12.2~rc2+focal_amd64.deb, core/focal/securedrop-app-code_2.12.2~rc2+focal_amd64.deb, core/focal/securedrop-config-dbgsym_2.12.2~rc2+focal_amd64.deb, core/focal/securedrop-config_2.12.2~rc2+focal_amd64.deb, core/focal/securedrop-keyring_0.2.2+2.12.2~rc2+focal_all.deb, core/focal/securedrop-ossec-agent_3.6.0+2.12.2~rc2+focal_all.deb, core/focal/securedrop-ossec-server_3.6.0+2.12.2~rc2+focal_all.deb, core/noble/securedrop-app-code-dbgsym_2.12.2~rc2+noble_amd64.deb, core/noble/securedrop-app-code_2.12.2~rc2+noble_amd64.deb, core/noble/securedrop-config-dbgsym_2.12.2~rc2+noble_amd64.deb, core/noble/securedrop-config_2.12.2~rc2+noble_amd64.deb, core/noble/securedrop-keyring_0.2.2+2.12.2~rc2+noble_all.deb, core/noble/securedrop-ossec-agent_3.6.0+2.12.2~rc2+noble_all.deb, core/noble/securedrop-ossec-server_3.6.0+2.12.2~rc2+noble_all.deb
=> Add SecureDrop 2.12.2-rc2 packages

core/focal/linux-headers-5.15.180-1-grsec-securedrop_5.15.180-1-grsec-securedrop-1_amd64.deb, core/focal/linux-image-5.15.180-1-grsec-securedrop_5.15.180-1-grsec-securedrop-1_amd64.deb, core/focal/securedrop-grsec_5.15.180-1-grsec-securedrop-1_amd64.deb, core/noble/linux-headers-6.6.88-1-grsec-securedrop_6.6.88-1-grsec-securedrop-1_amd64.deb, core/noble/linux-image-6.6.88-1-grsec-securedrop_6.6.88-1-grsec-securedrop-1_amd64.deb, core/noble/securedrop-grsec_6.6.88-1-grsec-securedrop-1_amd64.deb, workstation/bookworm/linux-headers-6.6.88-1-grsec-workstation_6.6.88-1-grsec-workstation-1_amd64.deb, workstation/bookworm/linux-image-6.6.88-1-grsec-workstation_6.6.88-1-grsec-workstation-1_amd64.deb, workstation/bookworm/securedrop-workstation-grsec_6.6.88-1-grsec-workstation-1_amd64.deb
Towards freedomofpress/securedrop#7511.
- v5.15.180: freedomofpress/build-logs@426208e71a21f96291b51f3f45bb874c3d094a6b
- v6.6.88: freedomofpress/build-logs@67da58c6c9ad552919abd650ec81af821a6a8ef2
=> April kernel update: Linux 5.15.180 and 6.6.88

workstation/bookworm/securedrop-client-dbgsym_0.15.0~rc1+bookworm_amd64.deb, workstation/bookworm/securedrop-client_0.15.0~rc1+bookworm_amd64.deb, workstation/bookworm/securedrop-export_0.15.0~rc1+bookworm_all.deb, workstation/bookworm/securedrop-keyring_0.15.0~rc1+bookworm_all.deb, workstation/bookworm/securedrop-log_0.15.0~rc1+bookworm_all.deb, workstation/bookworm/securedrop-proxy-dbgsym_0.15.0~rc1+bookworm_amd64.deb, workstation/bookworm/securedrop-proxy_0.15.0~rc1+bookworm_amd64.deb, workstation/bookworm/securedrop-qubesdb-tools_0.15.0~rc1+bookworm_all.deb, workstation/bookworm/securedrop-whonix-config_0.15.0~rc1+bookworm_all.deb, workstation/bookworm/securedrop-workstation-config_0.15.0~rc1+bookworm_all.deb, workstation/bookworm/securedrop-workstation-viewer_0.15.0~rc1+bookworm_all.deb
- see https://github.com/freedomofpress/build-logs/pull/13
=> Add SecureDrop Client 0.15.0-rc1 debs

.github/workflows/update-tor.yml
Because the database is now committed to Git, the `reprepro update` command is smarter and won't download the upstream debs if they're already present in the repository.
This is generally good, but we want copies in our core/{focal,noble} folders. Have reprepro update the copy in repo/public/pool, copy the latest version of those debs over to our core/ folders. Git will commit just the new core/ debs, and the next commit will trigger re-signing.
Refs #267.
=> Fix update-tor workflow

core/focal/securedrop-app-code-dbgsym_2.12.9~rc1+focal_amd64.deb, core/focal/securedrop-app-code_2.12.9~rc1+focal_amd64.deb, core/focal/securedrop-config-dbgsym_2.12.9~rc1+focal_amd64.deb, core/focal/securedrop-config_2.12.9~rc1+focal_amd64.deb, core/focal/securedrop-keyring_0.2.2+2.12.9~rc1+focal_all.deb, core/focal/securedrop-ossec-agent_3.6.0+2.12.9~rc1+focal_all.deb, core/focal/securedrop-ossec-server_3.6.0+2.12.9~rc1+focal_all.deb, core/noble/securedrop-app-code-dbgsym_2.12.9~rc1+noble_amd64.deb, core/noble/securedrop-app-code_2.12.9~rc1+noble_amd64.deb, core/noble/securedrop-config-dbgsym_2.12.9~rc1+noble_amd64.deb, core/noble/securedrop-config_2.12.9~rc1+noble_amd64.deb, core/noble/securedrop-keyring_0.2.2+2.12.9~rc1+noble_all.deb, core/noble/securedrop-ossec-agent_3.6.0+2.12.9~rc1+noble_all.deb, core/noble/securedrop-ossec-server_3.6.0+2.12.9~rc1+noble_all.deb
=> Add SecureDrop 2.12.9-rc1 packages.

workstation/bookworm/securedrop-arti-dbgsym_1.4.6+bookworm_amd64.deb, workstation/bookworm/securedrop-arti_1.4.6+bookworm_amd64.deb
Fixes <https://github.com/freedomofpress/securedrop-workstation/issues/1381>.
=> Add securedrop-arti 1.4.6

workstation/bookworm/securedrop-client-dbgsym_0.17.0~rc2+bookworm_amd64.deb, workstation/bookworm/securedrop-client_0.17.0~rc2+bookworm_amd64.deb, workstation/bookworm/securedrop-export_0.17.0~rc2+bookworm_all.deb, workstation/bookworm/securedrop-keyring_0.17.0~rc2+bookworm_all.deb, workstation/bookworm/securedrop-log_0.17.0~rc2+bookworm_all.deb, workstation/bookworm/securedrop-proxy-dbgsym_0.17.0~rc2+bookworm_amd64.deb, workstation/bookworm/securedrop-proxy_0.17.0~rc2+bookworm_amd64.deb, workstation/bookworm/securedrop-qubesdb-tools_0.17.0~rc2+bookworm_all.deb, workstation/bookworm/securedrop-workstation-config_0.17.0~rc2+bookworm_all.deb, workstation/bookworm/securedrop-workstation-viewer_0.17.0~rc2+bookworm_all.deb
Ready for review.
Add SecureDrop Client 0.17.0-rc1 packages. Build logs uploaded to https://github.com/freedomofpress/build-logs/commit/1459d2c5d9d154cb1747bc41065928cdac0af73f.
=> Add SecureDrop Client 0.17.0-rc2
